// JACK Wave 2 — Deep Dive Keywords
// This file is auto-merged by generate-seo.js
module.exports = [

// === BANKS ===
{
  slug:"biasiswa-maybank-2026",type:"scholarship",
  keywords:{primary:"Maybank scholarship 2026",primary_bm:"biasiswa Maybank 2026",
    longtail_en:["Maybank foundation scholarship","Yayasan Maybank education fund","Maybank scholarship application 2026","Maybank scholarship requirements"],
    longtail_bm:["biasiswa Yayasan Maybank","tabung pendidikan Maybank","permohonan biasiswa Maybank 2026","syarat biasiswa Maybank"]},
  meta:{title:"Maybank Scholarship 2026 | MyScholar",title_bm:"Biasiswa Maybank 2026 | MyScholar",
    description:"Yayasan Maybank scholarship for Malaysian students 2026. Finance, IT, and business study awards.",
    description_bm:"Biasiswa Yayasan Maybank untuk pelajar Malaysia 2026. Anugerah pengajian kewangan, IT, dan perniagaan."},
  landing:{h1_en:"Maybank Scholarship 2026",h1_bm:"Biasiswa Maybank 2026",
    intro_en:"As Malaysia's largest bank, Maybank invests in future talent through Yayasan Maybank's education programmes. Check if your field and grades qualify.",
    intro_bm:"Sebagai bank terbesar Malaysia, Maybank melabur dalam bakat masa depan melalui program pendidikan Yayasan Maybank. Semak jika bidang dan keputusan anda layak.",
    cta_en:"View Maybank Scholarship",cta_bm:"Lihat Biasiswa Maybank"}
},
{
  slug:"biasiswa-cimb-2026",type:"scholarship",
  keywords:{primary:"CIMB scholarship 2026",primary_bm:"biasiswa CIMB 2026",
    longtail_en:["CIMB foundation scholarship","Yayasan CIMB education award","CIMB scholarship malaysia 2026","CIMB bank scholarship application"],
    longtail_bm:["biasiswa Yayasan CIMB","anugerah pendidikan CIMB","biasiswa CIMB malaysia 2026","permohonan biasiswa bank CIMB"]},
  meta:{title:"CIMB Scholarship 2026 | MyScholar",title_bm:"Biasiswa CIMB 2026 | MyScholar",
    description:"CIMB Foundation scholarship opportunities for Malaysian students. Banking, finance, and technology focus.",
    description_bm:"Peluang biasiswa Yayasan CIMB untuk pelajar Malaysia. Fokus perbankan, kewangan, dan teknologi."},
  landing:{h1_en:"CIMB Scholarship 2026",h1_bm:"Biasiswa CIMB 2026",
    intro_en:"CIMB Foundation supports Malaysian students pursuing studies in banking, finance, and tech. If you're driven and academically strong, this is worth a look.",
    intro_bm:"Yayasan CIMB menyokong pelajar Malaysia yang mengejar pengajian perbankan, kewangan, dan teknologi. Jika anda bersemangat dan cemerlang, ini patut diterokai.",
    cta_en:"Check CIMB Scholarship",cta_bm:"Semak Biasiswa CIMB"}
},
{
  slug:"biasiswa-public-bank-2026",type:"scholarship",
  keywords:{primary:"Public Bank scholarship 2026",primary_bm:"biasiswa Public Bank 2026",
    longtail_en:["Public Bank foundation scholarship","Public Bank education award malaysia","Public Bank scholarship application","Public Bank berhad scholarship"],
    longtail_bm:["biasiswa Yayasan Public Bank","anugerah pendidikan Public Bank","permohonan biasiswa Public Bank","biasiswa Public Bank Berhad"]},
  meta:{title:"Public Bank Scholarship 2026 | MyScholar",title_bm:"Biasiswa Public Bank 2026 | MyScholar",
    description:"Public Bank Foundation scholarship for Malaysian students. Accounting, finance, and economics pathways.",
    description_bm:"Biasiswa Yayasan Public Bank untuk pelajar Malaysia. Laluan perakaunan, kewangan, dan ekonomi."},
  landing:{h1_en:"Public Bank Scholarship 2026",h1_bm:"Biasiswa Public Bank 2026",
    intro_en:"Public Bank Foundation offers scholarships for students in accounting, finance, and economics. Known for being well-structured and highly competitive.",
    intro_bm:"Yayasan Public Bank menawarkan biasiswa untuk pelajar perakaunan, kewangan, dan ekonomi. Terkenal kerana tersusun dan sangat kompetitif.",
    cta_en:"View Public Bank Scholarship",cta_bm:"Lihat Biasiswa Public Bank"}
},

// === GLCs ===
{
  slug:"biasiswa-sime-darby-2026",type:"scholarship",
  keywords:{primary:"Sime Darby scholarship 2026",primary_bm:"biasiswa Sime Darby 2026",
    longtail_en:["Yayasan Sime Darby scholarship","Sime Darby foundation education","Sime Darby scholarship overseas","Sime Darby scholarship engineering"],
    longtail_bm:["biasiswa Yayasan Sime Darby","tajaan pendidikan Sime Darby","biasiswa Sime Darby luar negara","biasiswa Sime Darby kejuruteraan"]},
  meta:{title:"Sime Darby Scholarship 2026 | MyScholar",title_bm:"Biasiswa Sime Darby 2026 | MyScholar",
    description:"Yayasan Sime Darby scholarship -- one of Malaysia's most generous GLC awards for local and overseas study.",
    description_bm:"Biasiswa Yayasan Sime Darby -- salah satu anugerah GLC paling dermawan Malaysia untuk pengajian dalam dan luar negara."},
  landing:{h1_en:"Sime Darby Scholarship 2026",h1_bm:"Biasiswa Sime Darby 2026",
    intro_en:"Yayasan Sime Darby is one of the most generous corporate scholarship providers in Malaysia, covering full tuition and living expenses for top students.",
    intro_bm:"Yayasan Sime Darby adalah antara penyedia biasiswa korporat paling dermawan di Malaysia, menanggung yuran penuh dan elaun sara hidup untuk pelajar cemerlang.",
    cta_en:"View Sime Darby Scholarship",cta_bm:"Lihat Biasiswa Sime Darby"}
},
{
  slug:"biasiswa-axiata-2026",type:"scholarship",
  keywords:{primary:"Axiata scholarship 2026",primary_bm:"biasiswa Axiata 2026",
    longtail_en:["Axiata foundation scholarship","Yayasan Axiata education fund","Axiata digital scholarship","Axiata young talent programme"],
    longtail_bm:["biasiswa Yayasan Axiata","tabung pendidikan Axiata","biasiswa digital Axiata","program bakat muda Axiata"]},
  meta:{title:"Axiata Scholarship 2026 | MyScholar",title_bm:"Biasiswa Axiata 2026 | MyScholar",
    description:"Axiata Foundation scholarship for tech and digital economy students. One of Malaysia's top telco sponsors.",
    description_bm:"Biasiswa Yayasan Axiata untuk pelajar teknologi dan ekonomi digital. Salah satu penaja telco terkemuka Malaysia."},
  landing:{h1_en:"Axiata Scholarship 2026",h1_bm:"Biasiswa Axiata 2026",
    intro_en:"Axiata invests in digital talent through Yayasan Axiata. If you're into tech, data, or engineering, this GLC scholarship is one to watch.",
    intro_bm:"Axiata melabur dalam bakat digital melalui Yayasan Axiata. Jika anda minat teknologi, data, atau kejuruteraan, biasiswa GLC ini patut diperhatikan.",
    cta_en:"Check Axiata Scholarship",cta_bm:"Semak Biasiswa Axiata"}
},
{
  slug:"biasiswa-gamuda-2026",type:"scholarship",
  keywords:{primary:"Gamuda scholarship 2026",primary_bm:"biasiswa Gamuda 2026",
    longtail_en:["Yayasan Gamuda scholarship","Gamuda engineering scholarship","Gamuda foundation education","Gamuda scholarship civil engineering"],
    longtail_bm:["biasiswa Yayasan Gamuda","biasiswa Gamuda kejuruteraan","tajaan pendidikan Gamuda","biasiswa Gamuda kejuruteraan awam"]},
  meta:{title:"Gamuda Scholarship 2026 | MyScholar",title_bm:"Biasiswa Gamuda 2026 | MyScholar",
    description:"Gamuda Foundation scholarship for engineering and construction students. Infrastructure giant investing in future builders.",
    description_bm:"Biasiswa Yayasan Gamuda untuk pelajar kejuruteraan dan pembinaan. Gergasi infrastruktur melabur dalam pembina masa depan."},
  landing:{h1_en:"Gamuda Scholarship 2026",h1_bm:"Biasiswa Gamuda 2026",
    intro_en:"Gamuda -- the company behind MRT and major highways -- offers scholarships for future engineers. Civil, mechanical, and electrical engineering students, take note.",
    intro_bm:"Gamuda -- syarikat di sebalik MRT dan lebuh raya utama -- menawarkan biasiswa untuk jurutera masa depan. Pelajar kejuruteraan awam, mekanikal, dan elektrik, ambil perhatian.",
    cta_en:"View Gamuda Scholarship",cta_bm:"Lihat Biasiswa Gamuda"}
},
{
  slug:"biasiswa-telekom-tm-2026",type:"scholarship",
  keywords:{primary:"TM Telekom scholarship 2026",primary_bm:"biasiswa TM Telekom 2026",
    longtail_en:["Telekom Malaysia scholarship","Yayasan TM scholarship 2026","TM digital scholarship","Telekom Malaysia education fund"],
    longtail_bm:["biasiswa Telekom Malaysia","biasiswa Yayasan TM 2026","biasiswa digital TM","tabung pendidikan Telekom Malaysia"]},
  meta:{title:"TM / Telekom Malaysia Scholarship 2026 | MyScholar",title_bm:"Biasiswa TM / Telekom Malaysia 2026 | MyScholar",
    description:"Yayasan TM scholarship for IT, engineering, and digital economy students. Malaysia's national telco education fund.",
    description_bm:"Biasiswa Yayasan TM untuk pelajar IT, kejuruteraan, dan ekonomi digital. Tabung pendidikan telko kebangsaan Malaysia."},
  landing:{h1_en:"TM / Telekom Malaysia Scholarship 2026",h1_bm:"Biasiswa TM / Telekom Malaysia 2026",
    intro_en:"Telekom Malaysia sponsors students through Yayasan TM, focusing on IT, networking, and digital skills. If telecoms or tech is your thing, check this one.",
    intro_bm:"Telekom Malaysia menaja pelajar melalui Yayasan TM, dengan fokus pada IT, rangkaian, dan kemahiran digital. Jika telekomunikasi atau teknologi minat anda, semak ini.",
    cta_en:"View TM Scholarship",cta_bm:"Lihat Biasiswa TM"}
},
{
  slug:"biasiswa-ytl-2026",type:"scholarship",
  keywords:{primary:"YTL scholarship 2026",primary_bm:"biasiswa YTL 2026",
    longtail_en:["YTL foundation scholarship","YTL corporation scholarship malaysia","YTL education fund 2026","YTL engineering scholarship"],
    longtail_bm:["biasiswa Yayasan YTL","biasiswa YTL Corporation","tabung pendidikan YTL 2026","biasiswa YTL kejuruteraan"]},
  meta:{title:"YTL Scholarship 2026 | MyScholar",title_bm:"Biasiswa YTL 2026 | MyScholar",
    description:"YTL Foundation scholarship for Malaysian students in engineering, business, and technology fields.",
    description_bm:"Biasiswa Yayasan YTL untuk pelajar Malaysia dalam bidang kejuruteraan, perniagaan, dan teknologi."},
  landing:{h1_en:"YTL Scholarship 2026",h1_bm:"Biasiswa YTL 2026",
    intro_en:"YTL Corporation supports students through its foundation, funding studies in engineering, business, and technology. A lesser-known but valuable option.",
    intro_bm:"YTL Corporation menyokong pelajar melalui yayasannya, membiayai pengajian kejuruteraan, perniagaan, dan teknologi. Pilihan kurang dikenali tapi bernilai.",
    cta_en:"Check YTL Scholarship",cta_bm:"Semak Biasiswa YTL"}
},

// === FOREIGN GOVERNMENTS ===
{
  slug:"biasiswa-jepun-mext-2026",type:"scholarship",
  keywords:{primary:"Japan MEXT scholarship Malaysia 2026",primary_bm:"biasiswa Jepun MEXT Malaysia 2026",
    longtail_en:["MEXT scholarship for malaysians","Japan government scholarship 2026","study in Japan scholarship malaysia","Japanese government scholarship application"],
    longtail_bm:["biasiswa MEXT untuk rakyat malaysia","biasiswa kerajaan Jepun 2026","biasiswa belajar di Jepun","permohonan biasiswa kerajaan Jepun"]},
  meta:{title:"Japan MEXT Scholarship for Malaysians 2026 | MyScholar",title_bm:"Biasiswa Jepun MEXT untuk Rakyat Malaysia 2026 | MyScholar",
    description:"Japan's MEXT scholarship -- fully funded study in Japan for Malaysian students. Tuition, living costs, and airfare covered.",
    description_bm:"Biasiswa MEXT Jepun -- pengajian ditanggung penuh di Jepun untuk pelajar Malaysia. Yuran, kos sara hidup, dan tambang kapal terbang ditanggung."},
  landing:{h1_en:"Japan MEXT Scholarship 2026",h1_bm:"Biasiswa MEXT Jepun 2026",
    intro_en:"The Japanese Government MEXT Scholarship is fully funded -- tuition, monthly stipend, and return airfare. Open to Malaysians for undergraduate, research, and training programmes.",
    intro_bm:"Biasiswa Kerajaan Jepun MEXT ditanggung sepenuhnya -- yuran, elaun bulanan, dan tambang pulang pergi. Terbuka untuk rakyat Malaysia bagi program prasiswazah, penyelidikan, dan latihan.",
    cta_en:"View MEXT Details",cta_bm:"Lihat Butiran MEXT"}
},
{
  slug:"biasiswa-korea-kgsp-2026",type:"scholarship",
  keywords:{primary:"Korea KGSP scholarship Malaysia 2026",primary_bm:"biasiswa Korea KGSP Malaysia 2026",
    longtail_en:["Korean government scholarship 2026","KGSP scholarship for malaysians","study in Korea scholarship","GKS scholarship malaysia"],
    longtail_bm:["biasiswa kerajaan Korea 2026","biasiswa KGSP untuk rakyat malaysia","biasiswa belajar di Korea","biasiswa GKS malaysia"]},
  meta:{title:"Korea KGSP/GKS Scholarship for Malaysians 2026 | MyScholar",title_bm:"Biasiswa Korea KGSP/GKS untuk Rakyat Malaysia 2026 | MyScholar",
    description:"Korean Government Scholarship (KGSP/GKS) for Malaysian students. Fully funded study in South Korea.",
    description_bm:"Biasiswa Kerajaan Korea (KGSP/GKS) untuk pelajar Malaysia. Pengajian ditanggung penuh di Korea Selatan."},
  landing:{h1_en:"Korea KGSP Scholarship 2026",h1_bm:"Biasiswa KGSP Korea 2026",
    intro_en:"South Korea's KGSP (also called GKS) is a fully funded scholarship covering Korean language training, tuition, and living costs. Increasingly popular with Malaysian students.",
    intro_bm:"KGSP Korea Selatan (juga dipanggil GKS) adalah biasiswa ditanggung penuh meliputi latihan bahasa Korea, yuran, dan kos sara hidup. Semakin popular di kalangan pelajar Malaysia.",
    cta_en:"View Korea Scholarship",cta_bm:"Lihat Biasiswa Korea"}
},
{
  slug:"biasiswa-turki-turkiye-burslari-2026",type:"scholarship",
  keywords:{primary:"Turkey Turkiye Burslari scholarship 2026",primary_bm:"biasiswa Turki Turkiye Burslari 2026",
    longtail_en:["Turkish government scholarship malaysians","Turkiye Burslari 2026 application","study in Turkey scholarship","Turkey scholarship fully funded"],
    longtail_bm:["biasiswa kerajaan Turki malaysia","permohonan Turkiye Burslari 2026","biasiswa belajar di Turki","biasiswa Turki ditanggung penuh"]},
  meta:{title:"Turkey Turkiye Burslari Scholarship 2026 | MyScholar",title_bm:"Biasiswa Turki Turkiye Burslari 2026 | MyScholar",
    description:"Turkiye Burslari -- Turkey's fully funded government scholarship. Open to Malaysians for all levels of study.",
    description_bm:"Turkiye Burslari -- biasiswa kerajaan Turki ditanggung penuh. Terbuka untuk rakyat Malaysia semua peringkat pengajian."},
  landing:{h1_en:"Turkiye Burslari Scholarship 2026",h1_bm:"Biasiswa Turkiye Burslari 2026",
    intro_en:"Turkey's government scholarship covers everything -- tuition, accommodation, monthly stipend, health insurance, and even Turkish language courses. One of the most generous programmes globally.",
    intro_bm:"Biasiswa kerajaan Turki menanggung semuanya -- yuran, penginapan, elaun bulanan, insurans kesihatan, dan kursus bahasa Turki. Salah satu program paling dermawan di dunia.",
    cta_en:"View Turkey Scholarship",cta_bm:"Lihat Biasiswa Turki"}
},
{
  slug:"biasiswa-chevening-uk-2026",type:"scholarship",
  keywords:{primary:"Chevening scholarship Malaysia 2026",primary_bm:"biasiswa Chevening UK Malaysia 2026",
    longtail_en:["UK Chevening scholarship for malaysians","British government scholarship 2026","study in UK scholarship malaysia","Chevening application guide"],
    longtail_bm:["biasiswa UK Chevening untuk rakyat malaysia","biasiswa kerajaan British 2026","biasiswa belajar di UK malaysia","panduan permohonan Chevening"]},
  meta:{title:"Chevening UK Scholarship for Malaysians 2026 | MyScholar",title_bm:"Biasiswa Chevening UK untuk Rakyat Malaysia 2026 | MyScholar",
    description:"UK Chevening Scholarship -- the British government's flagship award for future leaders. Fully funded Masters in the UK.",
    description_bm:"Biasiswa Chevening UK -- anugerah utama kerajaan British untuk pemimpin masa depan. Sarjana ditanggung penuh di UK."},
  landing:{h1_en:"Chevening UK Scholarship 2026",h1_bm:"Biasiswa Chevening UK 2026",
    intro_en:"Chevening is the UK government's global scholarship for emerging leaders. Fully funded one-year Masters at any UK university. Competitive but transformative.",
    intro_bm:"Chevening adalah biasiswa global kerajaan UK untuk pemimpin masa depan. Sarjana setahun ditanggung penuh di mana-mana universiti UK. Kompetitif tapi mengubah hidup.",
    cta_en:"View Chevening Details",cta_bm:"Lihat Butiran Chevening"}
},
{
  slug:"biasiswa-australia-2026",type:"scholarship",
  keywords:{primary:"Australia scholarship Malaysia 2026",primary_bm:"biasiswa Australia Malaysia 2026",
    longtail_en:["Australia Awards scholarship malaysia","study in Australia scholarship 2026","Australian government scholarship","DFAT scholarship malaysia"],
    longtail_bm:["biasiswa Australia Awards malaysia","biasiswa belajar di Australia 2026","biasiswa kerajaan Australia","biasiswa DFAT malaysia"]},
  meta:{title:"Australia Scholarships for Malaysians 2026 | MyScholar",title_bm:"Biasiswa Australia untuk Rakyat Malaysia 2026 | MyScholar",
    description:"Australian government and university scholarships for Malaysian students. Study in Melbourne, Sydney, and more.",
    description_bm:"Biasiswa kerajaan dan universiti Australia untuk pelajar Malaysia. Belajar di Melbourne, Sydney, dan lain-lain."},
  landing:{h1_en:"Australia Scholarships for Malaysians 2026",h1_bm:"Biasiswa Australia untuk Rakyat Malaysia 2026",
    intro_en:"Australia Awards, university-specific scholarships, and research funding -- there are multiple pathways for Malaysians to study in Australia with financial support.",
    intro_bm:"Australia Awards, biasiswa khusus universiti, dan pembiayaan penyelidikan -- ada pelbagai laluan untuk rakyat Malaysia belajar di Australia dengan sokongan kewangan.",
    cta_en:"Explore Australia Scholarships",cta_bm:"Terokai Biasiswa Australia"}
},
{
  slug:"biasiswa-china-csc-2026",type:"scholarship",
  keywords:{primary:"China CSC scholarship Malaysia 2026",primary_bm:"biasiswa China CSC Malaysia 2026",
    longtail_en:["Chinese government scholarship malaysians","CSC scholarship 2026","study in China scholarship","China scholarship council malaysia"],
    longtail_bm:["biasiswa kerajaan China malaysia","biasiswa CSC 2026","biasiswa belajar di China","biasiswa majlis biasiswa China"]},
  meta:{title:"China CSC Scholarship for Malaysians 2026 | MyScholar",title_bm:"Biasiswa China CSC untuk Rakyat Malaysia 2026 | MyScholar",
    description:"Chinese Government CSC Scholarship -- fully funded study in China. Engineering, medicine, business, and more.",
    description_bm:"Biasiswa Kerajaan China CSC -- pengajian ditanggung penuh di China. Kejuruteraan, perubatan, perniagaan, dan lain-lain."},
  landing:{h1_en:"China CSC Scholarship 2026",h1_bm:"Biasiswa CSC China 2026",
    intro_en:"The Chinese Government Scholarship through CSC covers tuition, accommodation, and a monthly stipend at top Chinese universities. Growing interest from Malaysian students.",
    intro_bm:"Biasiswa Kerajaan China melalui CSC menanggung yuran, penginapan, dan elaun bulanan di universiti terkemuka China. Semakin diminati pelajar Malaysia.",
    cta_en:"View China Scholarship",cta_bm:"Lihat Biasiswa China"}
},
{
  slug:"biasiswa-timur-tengah-arab-saudi-2026",type:"scholarship",
  keywords:{primary:"Middle East scholarship Malaysia 2026",primary_bm:"biasiswa Timur Tengah Arab Saudi 2026",
    longtail_en:["Saudi Arabia scholarship malaysians","Egypt Al-Azhar scholarship","Jordan scholarship malaysia","Islamic studies scholarship abroad"],
    longtail_bm:["biasiswa Arab Saudi rakyat malaysia","biasiswa Al-Azhar Mesir","biasiswa Jordan malaysia","biasiswa pengajian Islam luar negara"]},
  meta:{title:"Middle East Scholarships for Malaysians 2026 | MyScholar",title_bm:"Biasiswa Timur Tengah untuk Rakyat Malaysia 2026 | MyScholar",
    description:"Scholarships to study in the Middle East -- Saudi Arabia, Egypt, Jordan. Islamic studies, medicine, and more.",
    description_bm:"Biasiswa belajar di Timur Tengah -- Arab Saudi, Mesir, Jordan. Pengajian Islam, perubatan, dan lain-lain."},
  landing:{h1_en:"Middle East Scholarships 2026",h1_bm:"Biasiswa Timur Tengah 2026",
    intro_en:"Saudi Arabia, Egypt, Jordan, and other Middle Eastern countries offer scholarships to Malaysian students, particularly in Islamic studies, Arabic, and medicine.",
    intro_bm:"Arab Saudi, Mesir, Jordan, dan negara Timur Tengah lain menawarkan biasiswa kepada pelajar Malaysia, terutamanya dalam pengajian Islam, bahasa Arab, dan perubatan.",
    cta_en:"View Middle East Scholarships",cta_bm:"Lihat Biasiswa Timur Tengah"}
},
{
  slug:"biasiswa-new-zealand-2026",type:"scholarship",
  keywords:{primary:"New Zealand scholarship Malaysia 2026",primary_bm:"biasiswa New Zealand Malaysia 2026",
    longtail_en:["NZ scholarship for malaysians","New Zealand government scholarship","study in New Zealand 2026","Manaaki New Zealand scholarship"],
    longtail_bm:["biasiswa NZ untuk rakyat malaysia","biasiswa kerajaan New Zealand","biasiswa belajar di New Zealand","biasiswa Manaaki New Zealand"]},
  meta:{title:"New Zealand Scholarships for Malaysians 2026 | MyScholar",title_bm:"Biasiswa New Zealand untuk Rakyat Malaysia 2026 | MyScholar",
    description:"Manaaki New Zealand Scholarship and other NZ awards for Malaysian students. Fully funded postgraduate study.",
    description_bm:"Biasiswa Manaaki New Zealand dan anugerah NZ lain untuk pelajar Malaysia. Pengajian pascasiswazah ditanggung penuh."},
  landing:{h1_en:"New Zealand Scholarships 2026",h1_bm:"Biasiswa New Zealand 2026",
    intro_en:"New Zealand offers the Manaaki Scholarship and other awards for postgraduate study. Smaller applicant pools mean better odds than you might think.",
    intro_bm:"New Zealand menawarkan Biasiswa Manaaki dan anugerah lain untuk pengajian pascasiswazah. Jumlah pemohon lebih kecil bermakna peluang lebih tinggi daripada yang anda sangka.",
    cta_en:"View NZ Scholarships",cta_bm:"Lihat Biasiswa NZ"}
},

// === RELIGIOUS & COMMUNITY ===
{
  slug:"biasiswa-zakat-2026",type:"scholarship",
  keywords:{primary:"zakat scholarship malaysia 2026",primary_bm:"biasiswa zakat malaysia 2026",
    longtail_en:["zakat education fund malaysia","zakat scholarship for students","majlis agama zakat scholarship","Islamic scholarship zakat funded"],
    longtail_bm:["tabung pendidikan zakat malaysia","biasiswa zakat untuk pelajar","biasiswa majlis agama Islam","biasiswa tajaan zakat"]},
  meta:{title:"Zakat-Funded Scholarships Malaysia 2026 | MyScholar",title_bm:"Biasiswa Tajaan Zakat Malaysia 2026 | MyScholar",
    description:"Scholarships funded by zakat collections from state Islamic religious councils across Malaysia.",
    description_bm:"Biasiswa yang dibiayai kutipan zakat dari majlis agama Islam negeri di seluruh Malaysia."},
  landing:{h1_en:"Zakat-Funded Scholarships 2026",h1_bm:"Biasiswa Tajaan Zakat 2026",
    intro_en:"State Islamic religious councils distribute zakat funds for education. These scholarships are often under-applied -- and they're available in every state.",
    intro_bm:"Majlis agama Islam negeri mengagihkan dana zakat untuk pendidikan. Biasiswa ini sering kurang pemohon -- dan ia tersedia di setiap negeri.",
    cta_en:"Find Zakat Scholarships",cta_bm:"Cari Biasiswa Zakat"}
},
{
  slug:"biasiswa-yapeim-2026",type:"scholarship",
  keywords:{primary:"YAPEIM scholarship 2026",primary_bm:"biasiswa YAPEIM 2026",
    longtail_en:["YAPEIM education fund","Yayasan Pembangunan Ekonomi Islam scholarship","YAPEIM scholarship application","Islamic development scholarship malaysia"],
    longtail_bm:["tabung pendidikan YAPEIM","biasiswa Yayasan Pembangunan Ekonomi Islam","permohonan biasiswa YAPEIM","biasiswa pembangunan Islam malaysia"]},
  meta:{title:"YAPEIM Scholarship 2026 | MyScholar",title_bm:"Biasiswa YAPEIM 2026 | MyScholar",
    description:"YAPEIM (Yayasan Pembangunan Ekonomi Islam) scholarship for Muslim students in Malaysia.",
    description_bm:"Biasiswa YAPEIM (Yayasan Pembangunan Ekonomi Islam) untuk pelajar Islam Malaysia."},
  landing:{h1_en:"YAPEIM Scholarship 2026",h1_bm:"Biasiswa YAPEIM 2026",
    intro_en:"YAPEIM supports Muslim students through education scholarships and development programmes. One of the key Islamic economy foundations in Malaysia.",
    intro_bm:"YAPEIM menyokong pelajar Islam melalui biasiswa pendidikan dan program pembangunan. Salah satu yayasan ekonomi Islam utama di Malaysia.",
    cta_en:"View YAPEIM Scholarship",cta_bm:"Lihat Biasiswa YAPEIM"}
},
{
  slug:"biasiswa-tabung-haji-2026",type:"scholarship",
  keywords:{primary:"Tabung Haji scholarship 2026",primary_bm:"biasiswa Tabung Haji 2026",
    longtail_en:["TH scholarship malaysia","Lembaga Tabung Haji education","Tabung Haji scholarship application","TH education sponsorship 2026"],
    longtail_bm:["biasiswa TH malaysia","tajaan pendidikan Lembaga Tabung Haji","permohonan biasiswa Tabung Haji","tajaan pendidikan TH 2026"]},
  meta:{title:"Tabung Haji Scholarship 2026 | MyScholar",title_bm:"Biasiswa Tabung Haji 2026 | MyScholar",
    description:"Lembaga Tabung Haji education sponsorship for Malaysian Muslim students.",
    description_bm:"Tajaan pendidikan Lembaga Tabung Haji untuk pelajar Islam Malaysia."},
  landing:{h1_en:"Tabung Haji Scholarship 2026",h1_bm:"Biasiswa Tabung Haji 2026",
    intro_en:"Lembaga Tabung Haji offers education sponsorships for Malaysian Muslim students. If your family has TH savings, you may be eligible for additional education support.",
    intro_bm:"Lembaga Tabung Haji menawarkan tajaan pendidikan untuk pelajar Islam Malaysia. Jika keluarga anda ada simpanan TH, anda mungkin layak untuk sokongan pendidikan tambahan.",
    cta_en:"Check TH Scholarship",cta_bm:"Semak Biasiswa TH"}
},

// === MORE FIELDS OF STUDY ===
{
  slug:"biasiswa-undang-undang-law-2026",type:"scholarship",
  keywords:{primary:"law scholarship malaysia 2026",primary_bm:"biasiswa undang-undang malaysia 2026",
    longtail_en:["law student scholarship malaysia","LLB scholarship 2026","legal studies scholarship","Bar Council scholarship malaysia"],
    longtail_bm:["biasiswa pelajar undang-undang malaysia","biasiswa LLB 2026","biasiswa pengajian perundangan","biasiswa Majlis Peguam malaysia"]},
  meta:{title:"Law Scholarships Malaysia 2026 | MyScholar",title_bm:"Biasiswa Undang-Undang Malaysia 2026 | MyScholar",
    description:"Scholarships for law students in Malaysia. LLB, CLP, and legal studies funding from government and private sponsors.",
    description_bm:"Biasiswa untuk pelajar undang-undang Malaysia. Pembiayaan LLB, CLP, dan pengajian perundangan dari kerajaan dan penaja swasta."},
  landing:{h1_en:"Law Scholarships Malaysia 2026",h1_bm:"Biasiswa Undang-Undang Malaysia 2026",
    intro_en:"Law degrees are a significant investment. There are scholarships from the Bar Council, government bodies, and corporate foundations that specifically support aspiring lawyers.",
    intro_bm:"Ijazah undang-undang adalah pelaburan besar. Ada biasiswa dari Majlis Peguam, badan kerajaan, dan yayasan korporat yang khusus menyokong bakal peguam.",
    cta_en:"Find Law Scholarships",cta_bm:"Cari Biasiswa Undang-Undang"}
},
{
  slug:"biasiswa-farmasi-pharmacy-2026",type:"scholarship",
  keywords:{primary:"pharmacy scholarship malaysia 2026",primary_bm:"biasiswa farmasi malaysia 2026",
    longtail_en:["pharmacy student scholarship","pharmacist scholarship malaysia 2026","pharmaceutical scholarship","pharmacy degree funding"],
    longtail_bm:["biasiswa pelajar farmasi","biasiswa ahli farmasi malaysia 2026","biasiswa farmaseutikal","pembiayaan ijazah farmasi"]},
  meta:{title:"Pharmacy Scholarships Malaysia 2026 | MyScholar",title_bm:"Biasiswa Farmasi Malaysia 2026 | MyScholar",
    description:"Scholarships for pharmacy students in Malaysia 2026. Government, hospital, and pharmaceutical company sponsors.",
    description_bm:"Biasiswa untuk pelajar farmasi Malaysia 2026. Penaja kerajaan, hospital, dan syarikat farmaseutikal."},
  landing:{h1_en:"Pharmacy Scholarships Malaysia 2026",h1_bm:"Biasiswa Farmasi Malaysia 2026",
    intro_en:"Pharmacy is a growing field with strong demand. Government bodies and pharmaceutical companies offer scholarships to ensure the pipeline of qualified pharmacists continues.",
    intro_bm:"Farmasi adalah bidang yang berkembang dengan permintaan tinggi. Badan kerajaan dan syarikat farmaseutikal menawarkan biasiswa untuk memastikan bekalan ahli farmasi berkelayakan berterusan.",
    cta_en:"Browse Pharmacy Scholarships",cta_bm:"Layari Biasiswa Farmasi"}
},
{
  slug:"biasiswa-pergigian-dentistry-2026",type:"scholarship",
  keywords:{primary:"dentistry scholarship malaysia 2026",primary_bm:"biasiswa pergigian malaysia 2026",
    longtail_en:["dental scholarship malaysia","dentistry student scholarship 2026","BDS scholarship malaysia","dental surgery scholarship"],
    longtail_bm:["biasiswa pelajar pergigian","biasiswa pergigian 2026","biasiswa BDS malaysia","biasiswa pembedahan pergigian"]},
  meta:{title:"Dentistry Scholarships Malaysia 2026 | MyScholar",title_bm:"Biasiswa Pergigian Malaysia 2026 | MyScholar",
    description:"Scholarships for dentistry students in Malaysia. BDS and dental surgery funding.",
    description_bm:"Biasiswa untuk pelajar pergigian Malaysia. Pembiayaan BDS dan pembedahan pergigian."},
  landing:{h1_en:"Dentistry Scholarships Malaysia 2026",h1_bm:"Biasiswa Pergigian Malaysia 2026",
    intro_en:"Dental degrees are among the most expensive programmes. JPA and several private sponsors offer funding for BDS and dental surgery students.",
    intro_bm:"Ijazah pergigian antara program paling mahal. JPA dan beberapa penaja swasta menawarkan pembiayaan untuk pelajar BDS dan pembedahan pergigian.",
    cta_en:"Find Dentistry Scholarships",cta_bm:"Cari Biasiswa Pergigian"}
},
{
  slug:"biasiswa-kejururawatan-nursing-2026",type:"scholarship",
  keywords:{primary:"nursing scholarship malaysia 2026",primary_bm:"biasiswa kejururawatan malaysia 2026",
    longtail_en:["nursing student scholarship","nursing degree scholarship malaysia","hospital nursing scholarship 2026","KPJ nursing scholarship"],
    longtail_bm:["biasiswa pelajar kejururawatan","biasiswa ijazah kejururawatan","biasiswa kejururawatan hospital 2026","biasiswa kejururawatan KPJ"]},
  meta:{title:"Nursing Scholarships Malaysia 2026 | MyScholar",title_bm:"Biasiswa Kejururawatan Malaysia 2026 | MyScholar",
    description:"Scholarships for nursing students in Malaysia 2026. Government hospitals, private healthcare, and MOH sponsorships.",
    description_bm:"Biasiswa untuk pelajar kejururawatan Malaysia 2026. Hospital kerajaan, penjagaan kesihatan swasta, dan tajaan KKM."},
  landing:{h1_en:"Nursing Scholarships Malaysia 2026",h1_bm:"Biasiswa Kejururawatan Malaysia 2026",
    intro_en:"Malaysia needs nurses, and both government and private hospitals fund nursing education through scholarships. Often with guaranteed employment upon graduation.",
    intro_bm:"Malaysia memerlukan jururawat, dan hospital kerajaan serta swasta membiayai pendidikan kejururawatan melalui biasiswa. Sering dengan jaminan pekerjaan selepas tamat pengajian.",
    cta_en:"View Nursing Scholarships",cta_bm:"Lihat Biasiswa Kejururawatan"}
},
{
  slug:"biasiswa-penerbangan-aviation-2026",type:"scholarship",
  keywords:{primary:"aviation scholarship malaysia 2026",primary_bm:"biasiswa penerbangan malaysia 2026",
    longtail_en:["pilot scholarship malaysia 2026","aviation cadet scholarship","Malaysia Airlines pilot scholarship","AirAsia pilot programme scholarship"],
    longtail_bm:["biasiswa juruterbang malaysia 2026","biasiswa kadet penerbangan","biasiswa juruterbang Malaysia Airlines","biasiswa program juruterbang AirAsia"]},
  meta:{title:"Aviation & Pilot Scholarships Malaysia 2026 | MyScholar",title_bm:"Biasiswa Penerbangan & Juruterbang Malaysia 2026 | MyScholar",
    description:"Aviation and pilot scholarships in Malaysia. Airline cadet programmes and aerospace engineering funding.",
    description_bm:"Biasiswa penerbangan dan juruterbang Malaysia. Program kadet syarikat penerbangan dan pembiayaan kejuruteraan aeroangkasa."},
  landing:{h1_en:"Aviation & Pilot Scholarships 2026",h1_bm:"Biasiswa Penerbangan & Juruterbang 2026",
    intro_en:"Becoming a pilot is expensive, but airlines like Malaysia Airlines and AirAsia run cadet programmes with full sponsorship. Aerospace engineering scholarships also available.",
    intro_bm:"Menjadi juruterbang memang mahal, tapi syarikat penerbangan seperti Malaysia Airlines dan AirAsia menjalankan program kadet dengan tajaan penuh. Biasiswa kejuruteraan aeroangkasa juga tersedia.",
    cta_en:"Explore Aviation Scholarships",cta_bm:"Terokai Biasiswa Penerbangan"}
},
{
  slug:"biasiswa-seni-creative-arts-2026",type:"scholarship",
  keywords:{primary:"arts scholarship malaysia 2026",primary_bm:"biasiswa seni malaysia 2026",
    longtail_en:["creative arts scholarship malaysia","design scholarship malaysia 2026","music scholarship malaysia","fine arts scholarship"],
    longtail_bm:["biasiswa seni kreatif malaysia","biasiswa reka bentuk malaysia 2026","biasiswa muzik malaysia","biasiswa seni halus"]},
  meta:{title:"Arts & Creative Scholarships Malaysia 2026 | MyScholar",title_bm:"Biasiswa Seni & Kreatif Malaysia 2026 | MyScholar",
    description:"Scholarships for arts, design, music, and creative students in Malaysia 2026.",
    description_bm:"Biasiswa untuk pelajar seni, reka bentuk, muzik, dan kreatif Malaysia 2026."},
  landing:{h1_en:"Arts & Creative Scholarships 2026",h1_bm:"Biasiswa Seni & Kreatif 2026",
    intro_en:"Creative fields are often overlooked in scholarship lists. But there are awards for design, music, film, and fine arts students -- from Cendana, ASWARA, and private foundations.",
    intro_bm:"Bidang kreatif sering terlepas pandang dalam senarai biasiswa. Tapi ada anugerah untuk pelajar reka bentuk, muzik, filem, dan seni halus -- dari Cendana, ASWARA, dan yayasan swasta.",
    cta_en:"Find Arts Scholarships",cta_bm:"Cari Biasiswa Seni"}
},
{
  slug:"biasiswa-pertanian-agriculture-2026",type:"scholarship",
  keywords:{primary:"agriculture scholarship malaysia 2026",primary_bm:"biasiswa pertanian malaysia 2026",
    longtail_en:["farming scholarship malaysia","agribusiness scholarship 2026","Felda scholarship","plantation scholarship malaysia"],
    longtail_bm:["biasiswa peladang malaysia","biasiswa perniagaan tani 2026","biasiswa Felda","biasiswa perladangan malaysia"]},
  meta:{title:"Agriculture Scholarships Malaysia 2026 | MyScholar",title_bm:"Biasiswa Pertanian Malaysia 2026 | MyScholar",
    description:"Scholarships for agriculture, agribusiness, and plantation management students.",
    description_bm:"Biasiswa untuk pelajar pertanian, perniagaan tani, dan pengurusan perladangan."},
  landing:{h1_en:"Agriculture Scholarships Malaysia 2026",h1_bm:"Biasiswa Pertanian Malaysia 2026",
    intro_en:"Agriculture remains a backbone of Malaysia's economy. Felda, Sime Darby, and government bodies sponsor students in agriculture, agritech, and plantation management.",
    intro_bm:"Pertanian kekal sebagai tulang belakang ekonomi Malaysia. Felda, Sime Darby, dan badan kerajaan menaja pelajar dalam pertanian, agriteknologi, dan pengurusan perladangan.",
    cta_en:"Browse Agriculture Scholarships",cta_bm:"Layari Biasiswa Pertanian"}
},
{
  slug:"biasiswa-perniagaan-business-2026",type:"scholarship",
  keywords:{primary:"business scholarship malaysia 2026",primary_bm:"biasiswa perniagaan malaysia 2026",
    longtail_en:["BBA scholarship malaysia","business administration scholarship 2026","MBA scholarship malaysia","entrepreneurship scholarship"],
    longtail_bm:["biasiswa BBA malaysia","biasiswa pentadbiran perniagaan 2026","biasiswa MBA malaysia","biasiswa keusahawanan"]},
  meta:{title:"Business Scholarships Malaysia 2026 | MyScholar",title_bm:"Biasiswa Perniagaan Malaysia 2026 | MyScholar",
    description:"Scholarships for business, BBA, MBA, and entrepreneurship students in Malaysia 2026.",
    description_bm:"Biasiswa untuk pelajar perniagaan, BBA, MBA, dan keusahawanan di Malaysia 2026."},
  landing:{h1_en:"Business Scholarships Malaysia 2026",h1_bm:"Biasiswa Perniagaan Malaysia 2026",
    intro_en:"From BBA to MBA, business students have access to corporate scholarships, bank-sponsored awards, and government funding.",
    intro_bm:"Dari BBA ke MBA, pelajar perniagaan mempunyai akses kepada biasiswa korporat, anugerah tajaan bank, dan pembiayaan kerajaan.",
    cta_en:"Find Business Scholarships",cta_bm:"Cari Biasiswa Perniagaan"}
},

// === PRE-UNIVERSITY ===
{
  slug:"biasiswa-matrikulasi-2026",type:"scholarship",
  keywords:{primary:"matriculation scholarship malaysia 2026",primary_bm:"biasiswa matrikulasi malaysia 2026",
    longtail_en:["matrikulasi scholarship 2026","pre-university scholarship malaysia","foundation programme scholarship","matrikulasi KPM scholarship"],
    longtail_bm:["biasiswa matrikulasi KPM 2026","biasiswa pra-universiti malaysia","biasiswa program asasi","biasiswa matrikulasi sains"]},
  meta:{title:"Matriculation & Pre-University Scholarships 2026 | MyScholar",title_bm:"Biasiswa Matrikulasi & Pra-Universiti 2026 | MyScholar",
    description:"Scholarships for matriculation and pre-university students in Malaysia.",
    description_bm:"Biasiswa untuk pelajar matrikulasi dan pra-universiti Malaysia."},
  landing:{h1_en:"Matriculation & Pre-University Scholarships 2026",h1_bm:"Biasiswa Matrikulasi & Pra-Universiti 2026",
    intro_en:"Between SPM and university, there's the pre-university gap. Foundation programmes, matrikulasi, and A-Levels -- some come with scholarships attached.",
    intro_bm:"Antara SPM dan universiti, ada jurang pra-universiti. Program asasi, matrikulasi, dan A-Levels -- ada yang datang dengan biasiswa.",
    cta_en:"Search Pre-U Scholarships",cta_bm:"Cari Biasiswa Pra-U"}
},
{
  slug:"biasiswa-a-levels-2026",type:"scholarship",
  keywords:{primary:"A-Levels scholarship malaysia 2026",primary_bm:"biasiswa A-Levels malaysia 2026",
    longtail_en:["A-Level scholarship for SPM leavers","Cambridge A-Level scholarship malaysia","pre-university A-Level funding","A-Level tuition scholarship"],
    longtail_bm:["biasiswa A-Level lepasan SPM","biasiswa Cambridge A-Level malaysia","pembiayaan pra-universiti A-Level","biasiswa yuran A-Level"]},
  meta:{title:"A-Levels Scholarships Malaysia 2026 | MyScholar",title_bm:"Biasiswa A-Levels Malaysia 2026 | MyScholar",
    description:"Scholarships for A-Level students in Malaysia. College-specific and sponsor-funded programmes.",
    description_bm:"Biasiswa untuk pelajar A-Level di Malaysia. Program tajaan kolej dan penaja."},
  landing:{h1_en:"A-Levels Scholarships Malaysia 2026",h1_bm:"Biasiswa A-Levels Malaysia 2026",
    intro_en:"A-Levels can be expensive at private colleges. But several colleges and corporate sponsors offer full or partial scholarships for high-achieving SPM students.",
    intro_bm:"A-Levels boleh jadi mahal di kolej swasta. Tapi beberapa kolej dan penaja korporat menawarkan biasiswa penuh atau separa untuk pelajar SPM cemerlang.",
    cta_en:"Find A-Level Scholarships",cta_bm:"Cari Biasiswa A-Level"}
},

// === INDIVIDUAL STATES ===
{
  slug:"biasiswa-selangor-2026",type:"scholarship",
  keywords:{primary:"Selangor scholarship 2026",primary_bm:"biasiswa Selangor 2026",
    longtail_en:["Selangor state scholarship","Yayasan Selangor scholarship 2026","MBSA scholarship","Selangor government education fund"],
    longtail_bm:["biasiswa kerajaan negeri Selangor","biasiswa Yayasan Selangor 2026","biasiswa MBSA","tabung pendidikan kerajaan Selangor"]},
  meta:{title:"Selangor Scholarships 2026 | MyScholar",title_bm:"Biasiswa Selangor 2026 | MyScholar",
    description:"All scholarships from Selangor state government and Yayasan Selangor for 2026.",
    description_bm:"Semua biasiswa kerajaan negeri Selangor dan Yayasan Selangor 2026."},
  landing:{h1_en:"Selangor Scholarships 2026",h1_bm:"Biasiswa Selangor 2026",
    intro_en:"Selangor, as Malaysia's most populous state, runs several scholarship programmes through Yayasan Selangor and state agencies.",
    intro_bm:"Selangor, sebagai negeri paling ramai penduduk di Malaysia, menjalankan beberapa program biasiswa melalui Yayasan Selangor dan agensi negeri.",
    cta_en:"View Selangor Scholarships",cta_bm:"Lihat Biasiswa Selangor"}
},
{
  slug:"biasiswa-johor-2026",type:"scholarship",
  keywords:{primary:"Johor scholarship 2026",primary_bm:"biasiswa Johor 2026",
    longtail_en:["Johor state scholarship","Yayasan Pelajaran Johor","YPJB scholarship 2026","Johor government education fund"],
    longtail_bm:["biasiswa kerajaan negeri Johor","Yayasan Pelajaran Johor Berhad","biasiswa YPJB 2026","tabung pendidikan kerajaan Johor"]},
  meta:{title:"Johor Scholarships 2026 | MyScholar",title_bm:"Biasiswa Johor 2026 | MyScholar",
    description:"Johor state scholarships 2026. YPJB and Johor government education programmes.",
    description_bm:"Biasiswa negeri Johor 2026. YPJB dan program pendidikan kerajaan Johor."},
  landing:{h1_en:"Johor Scholarships 2026",h1_bm:"Biasiswa Johor 2026",
    intro_en:"Yayasan Pelajaran Johor (YPJB) and the Johor state government fund education for students from the state.",
    intro_bm:"Yayasan Pelajaran Johor (YPJB) dan kerajaan negeri Johor membiayai pendidikan untuk pelajar dari negeri ini.",
    cta_en:"Check Johor Scholarships",cta_bm:"Semak Biasiswa Johor"}
},
{
  slug:"biasiswa-pulau-pinang-penang-2026",type:"scholarship",
  keywords:{primary:"Penang scholarship 2026",primary_bm:"biasiswa Pulau Pinang 2026",
    longtail_en:["Penang state scholarship","Penang government education fund","Penang foundation scholarship 2026","scholarship for Penang students"],
    longtail_bm:["biasiswa kerajaan negeri Pulau Pinang","tabung pendidikan Pulau Pinang","biasiswa yayasan Pulau Pinang 2026","biasiswa pelajar Pulau Pinang"]},
  meta:{title:"Penang Scholarships 2026 | MyScholar",title_bm:"Biasiswa Pulau Pinang 2026 | MyScholar",
    description:"Scholarships from Penang state government for 2026.",
    description_bm:"Biasiswa kerajaan negeri Pulau Pinang 2026."},
  landing:{h1_en:"Penang Scholarships 2026",h1_bm:"Biasiswa Pulau Pinang 2026",
    intro_en:"Penang runs its own education awards for students from the state. If you're Penang-born, start here.",
    intro_bm:"Pulau Pinang menjalankan anugerah pendidikan sendiri untuk pelajar dari negeri ini. Jika anda kelahiran Pulau Pinang, mulakan di sini.",
    cta_en:"View Penang Scholarships",cta_bm:"Lihat Biasiswa Pulau Pinang"}
},
{
  slug:"biasiswa-perak-2026",type:"scholarship",
  keywords:{primary:"Perak scholarship 2026",primary_bm:"biasiswa Perak 2026",
    longtail_en:["Perak state scholarship","Yayasan Perak scholarship 2026","Perak government education fund","scholarship for Perak students"],
    longtail_bm:["biasiswa kerajaan negeri Perak","biasiswa Yayasan Perak 2026","tabung pendidikan kerajaan Perak","biasiswa pelajar Perak"]},
  meta:{title:"Perak Scholarships 2026 | MyScholar",title_bm:"Biasiswa Perak 2026 | MyScholar",
    description:"Perak state scholarships and education awards for 2026.",
    description_bm:"Biasiswa dan anugerah pendidikan negeri Perak 2026."},
  landing:{h1_en:"Perak Scholarships 2026",h1_bm:"Biasiswa Perak 2026",
    intro_en:"Perak offers its own state scholarships through Yayasan Perak. Often less competitive than federal awards -- reserved for Perak-born students.",
    intro_bm:"Perak menawarkan biasiswa negeri sendiri melalui Yayasan Perak. Sering kurang kompetitif berbanding anugerah persekutuan -- dikhaskan untuk pelajar kelahiran Perak.",
    cta_en:"Check Perak Scholarships",cta_bm:"Semak Biasiswa Perak"}
},
{
  slug:"biasiswa-kedah-2026",type:"scholarship",
  keywords:{primary:"Kedah scholarship 2026",primary_bm:"biasiswa Kedah 2026",
    longtail_en:["Kedah state scholarship","Yayasan Kedah scholarship","Kedah government education fund","scholarship for Kedah students"],
    longtail_bm:["biasiswa kerajaan negeri Kedah","biasiswa Yayasan Kedah","tabung pendidikan Kedah","biasiswa pelajar Kedah"]},
  meta:{title:"Kedah Scholarships 2026 | MyScholar",title_bm:"Biasiswa Kedah 2026 | MyScholar",
    description:"Kedah state education scholarships for 2026.",
    description_bm:"Biasiswa pendidikan negeri Kedah 2026."},
  landing:{h1_en:"Kedah Scholarships 2026",h1_bm:"Biasiswa Kedah 2026",
    intro_en:"Kedah's state government and local foundations provide education funding for students from the state.",
    intro_bm:"Kerajaan negeri Kedah dan yayasan tempatan menyediakan pembiayaan pendidikan untuk pelajar dari negeri ini.",
    cta_en:"View Kedah Scholarships",cta_bm:"Lihat Biasiswa Kedah"}
},
{
  slug:"biasiswa-kelantan-terengganu-2026",type:"scholarship",
  keywords:{primary:"Kelantan Terengganu scholarship 2026",primary_bm:"biasiswa Kelantan Terengganu 2026",
    longtail_en:["Kelantan state scholarship","Terengganu state scholarship 2026","East Coast scholarship malaysia","Yayasan Terengganu scholarship"],
    longtail_bm:["biasiswa negeri Kelantan","biasiswa negeri Terengganu 2026","biasiswa Pantai Timur malaysia","biasiswa Yayasan Terengganu"]},
  meta:{title:"Kelantan & Terengganu Scholarships 2026 | MyScholar",title_bm:"Biasiswa Kelantan & Terengganu 2026 | MyScholar",
    description:"State scholarships from Kelantan and Terengganu for 2026.",
    description_bm:"Biasiswa negeri Kelantan dan Terengganu 2026."},
  landing:{h1_en:"Kelantan & Terengganu Scholarships 2026",h1_bm:"Biasiswa Kelantan & Terengganu 2026",
    intro_en:"Students from Kelantan and Terengganu have access to state-specific scholarships from local foundations and oil royalty-funded education programmes.",
    intro_bm:"Pelajar dari Kelantan dan Terengganu mempunyai akses kepada biasiswa khusus negeri dari yayasan tempatan dan program pendidikan dibiayai royalti minyak.",
    cta_en:"Check East Coast Scholarships",cta_bm:"Semak Biasiswa Pantai Timur"}
},

// === PAIN POINTS / COMPARISON / DEADLINES ===
{
  slug:"ptptn-vs-biasiswa-2026",type:"scholarship",
  keywords:{primary:"PTPTN vs scholarship malaysia 2026",primary_bm:"PTPTN vs biasiswa malaysia 2026",
    longtail_en:["PTPTN or scholarship which better","alternative to PTPTN loan","scholarship instead of PTPTN","PTPTN repayment vs scholarship free"],
    longtail_bm:["PTPTN atau biasiswa mana lebih baik","alternatif pinjaman PTPTN","biasiswa ganti PTPTN","bayaran balik PTPTN vs biasiswa percuma"]},
  meta:{title:"PTPTN vs Scholarships -- Which Is Better? | MyScholar",title_bm:"PTPTN vs Biasiswa -- Mana Lebih Baik? | MyScholar",
    description:"Should you take PTPTN or find a scholarship? Compare loan vs free funding on MyScholar.",
    description_bm:"Patut ambil PTPTN atau cari biasiswa? Bandingkan pinjaman vs pembiayaan percuma di MyScholar."},
  landing:{h1_en:"PTPTN vs Scholarships: Which Path?",h1_bm:"PTPTN vs Biasiswa: Mana Laluan Anda?",
    intro_en:"PTPTN is a loan you pay back. Scholarships are free money. Before you default to PTPTN, check if there's a scholarship you qualify for -- there are more than you think.",
    intro_bm:"PTPTN adalah pinjaman yang perlu dibayar balik. Biasiswa adalah wang percuma. Sebelum anda terus ambil PTPTN, semak jika ada biasiswa yang anda layak -- ada lebih banyak daripada yang anda sangka.",
    cta_en:"Find Scholarships First",cta_bm:"Cari Biasiswa Dulu"}
},
{
  slug:"biasiswa-ditolak-tips-2026",type:"scholarship",
  keywords:{primary:"scholarship rejected what to do 2026",primary_bm:"biasiswa ditolak apa perlu buat 2026",
    longtail_en:["scholarship application rejected malaysia","appeal scholarship rejection","why scholarship rejected","reapply scholarship tips"],
    longtail_bm:["permohonan biasiswa ditolak malaysia","rayuan biasiswa ditolak","kenapa biasiswa ditolak","tips mohon semula biasiswa"]},
  meta:{title:"Scholarship Rejected? What To Do Next | MyScholar",title_bm:"Biasiswa Ditolak? Apa Perlu Buat Seterusnya | MyScholar",
    description:"Scholarship rejected? Don't give up. Here's how to appeal, reapply, or find alternatives in Malaysia.",
    description_bm:"Biasiswa ditolak? Jangan putus asa. Ini cara merayu, mohon semula, atau cari alternatif di Malaysia."},
  landing:{h1_en:"Scholarship Rejected? Here's What to Do",h1_bm:"Biasiswa Ditolak? Ini Apa Perlu Buat",
    intro_en:"Rejection stings, but it's not the end. There are hundreds of scholarships in Malaysia, and you only need one to say yes.",
    intro_bm:"Penolakan memang sakit, tapi ia bukan penghujung. Ada ratusan biasiswa di Malaysia, dan anda hanya perlu satu yang kata ya.",
    cta_en:"Browse All Scholarships",cta_bm:"Layari Semua Biasiswa"}
},
{
  slug:"biasiswa-2026-tarikh-tutup-april-mei",type:"scholarship",
  keywords:{primary:"scholarship deadline april may 2026 malaysia",primary_bm:"biasiswa tarikh tutup april mei 2026",
    longtail_en:["scholarships closing april 2026","scholarship deadline may 2026 malaysia","urgent scholarship application 2026","last minute scholarship malaysia"],
    longtail_bm:["biasiswa tutup april 2026","tarikh tutup biasiswa mei 2026","permohonan biasiswa segera 2026","biasiswa saat akhir malaysia"]},
  meta:{title:"Scholarships Closing April & May 2026 | MyScholar",title_bm:"Biasiswa Tarikh Tutup April & Mei 2026 | MyScholar",
    description:"Scholarships closing soon in April and May 2026. Don't miss these deadlines.",
    description_bm:"Biasiswa yang hampir tutup April dan Mei 2026. Jangan terlepas tarikh akhir ini."},
  landing:{h1_en:"Scholarships Closing April & May 2026",h1_bm:"Biasiswa Tutup April & Mei 2026",
    intro_en:"April and May are peak scholarship months in Malaysia. If you haven't applied yet, time is running out.",
    intro_bm:"April dan Mei adalah bulan puncak biasiswa di Malaysia. Jika anda belum mohon, masa semakin suntuk.",
    cta_en:"See Closing Deadlines",cta_bm:"Lihat Tarikh Tutup"}
},
{
  slug:"biasiswa-sukan-sports-2026",type:"scholarship",
  keywords:{primary:"sports scholarship malaysia 2026",primary_bm:"biasiswa sukan malaysia 2026",
    longtail_en:["athlete scholarship malaysia","sports education fund","scholarship for national athletes","MSN sports scholarship"],
    longtail_bm:["biasiswa atlet malaysia","tabung pendidikan sukan","biasiswa atlet kebangsaan","biasiswa sukan MSN"]},
  meta:{title:"Sports Scholarships Malaysia 2026 | MyScholar",title_bm:"Biasiswa Sukan Malaysia 2026 | MyScholar",
    description:"Scholarships for Malaysian athletes and sports students.",
    description_bm:"Biasiswa untuk atlet dan pelajar sukan Malaysia."},
  landing:{h1_en:"Sports Scholarships Malaysia 2026",h1_bm:"Biasiswa Sukan Malaysia 2026",
    intro_en:"If you're a competitive athlete, your talent can fund your education. National sports bodies, state associations, and universities offer scholarships for student-athletes.",
    intro_bm:"Jika anda atlet kompetitif, bakat anda boleh membiayai pendidikan anda. Badan sukan kebangsaan, persatuan negeri, dan universiti menawarkan biasiswa untuk pelajar-atlet.",
    cta_en:"Find Sports Scholarships",cta_bm:"Cari Biasiswa Sukan"}
},
{
  slug:"biasiswa-wanita-perempuan-2026",type:"scholarship",
  keywords:{primary:"scholarship for women malaysia 2026",primary_bm:"biasiswa wanita perempuan malaysia 2026",
    longtail_en:["women in STEM scholarship malaysia","female scholarship 2026","girls education scholarship","women empowerment scholarship malaysia"],
    longtail_bm:["biasiswa wanita STEM malaysia","biasiswa perempuan 2026","biasiswa pendidikan anak perempuan","biasiswa pemerkasaan wanita malaysia"]},
  meta:{title:"Scholarships for Women Malaysia 2026 | MyScholar",title_bm:"Biasiswa untuk Wanita Malaysia 2026 | MyScholar",
    description:"Scholarships specifically for women and girls in Malaysia 2026.",
    description_bm:"Biasiswa khas untuk wanita dan gadis Malaysia 2026."},
  landing:{h1_en:"Scholarships for Women 2026",h1_bm:"Biasiswa untuk Wanita 2026",
    intro_en:"Several scholarships in Malaysia specifically support women -- especially in STEM, leadership, and underrepresented fields.",
    intro_bm:"Beberapa biasiswa di Malaysia khusus menyokong wanita -- terutamanya dalam STEM, kepimpinan, dan bidang kurang diwakili.",
    cta_en:"Browse Women's Scholarships",cta_bm:"Layari Biasiswa Wanita"}
},

// === INTERNSHIP DEEP DIVE ===
{
  slug:"internship-kejuruteraan-engineering-2026",type:"internship",
  keywords:{primary:"engineering internship malaysia 2026",primary_bm:"latihan industri kejuruteraan malaysia 2026",
    longtail_en:["mechanical engineering internship malaysia","civil engineering internship 2026","electrical engineering internship","intern engineer malaysia"],
    longtail_bm:["latihan industri kejuruteraan mekanikal","latihan industri kejuruteraan awam 2026","latihan industri kejuruteraan elektrik","jurutera pelatih malaysia"]},
  meta:{title:"Engineering Internships Malaysia 2026 | MyScholar",title_bm:"Latihan Industri Kejuruteraan Malaysia 2026 | MyScholar",
    description:"Engineering internships across Malaysia 2026. Mechanical, civil, electrical, and chemical engineering.",
    description_bm:"Latihan industri kejuruteraan seluruh Malaysia 2026."},
  landing:{h1_en:"Engineering Internships Malaysia 2026",h1_bm:"Latihan Industri Kejuruteraan 2026",
    intro_en:"Engineering students -- find your internship placement here. We list opportunities across mechanical, civil, electrical, and chemical engineering.",
    intro_bm:"Pelajar kejuruteraan -- cari penempatan latihan industri anda di sini. Kami senaraikan peluang merentasi kejuruteraan mekanikal, awam, elektrik, dan kimia.",
    cta_en:"Search Engineering Internships",cta_bm:"Cari Latihan Industri Kejuruteraan"}
},
{
  slug:"internship-it-teknologi-2026",type:"internship",
  keywords:{primary:"IT internship malaysia 2026",primary_bm:"latihan industri IT teknologi malaysia 2026",
    longtail_en:["software developer internship malaysia","tech internship 2026","data science internship malaysia","cybersecurity internship"],
    longtail_bm:["latihan industri pembangun perisian","latihan industri teknologi 2026","latihan industri sains data","latihan industri keselamatan siber"]},
  meta:{title:"IT & Tech Internships Malaysia 2026 | MyScholar",title_bm:"Latihan Industri IT & Teknologi Malaysia 2026 | MyScholar",
    description:"IT and tech internships in Malaysia 2026. Software, data science, cybersecurity.",
    description_bm:"Latihan industri IT dan teknologi Malaysia 2026."},
  landing:{h1_en:"IT & Tech Internships Malaysia 2026",h1_bm:"Latihan Industri IT & Teknologi 2026",
    intro_en:"Tech internships are everywhere -- from startups in Bangsar South to GLCs in Cyberjaya. We track software, data, cloud, and cybersecurity placements.",
    intro_bm:"Latihan industri teknologi ada di mana-mana -- dari startup di Bangsar South ke GLC di Cyberjaya. Kami jejaki penempatan perisian, data, awan, dan keselamatan siber.",
    cta_en:"Find Tech Internships",cta_bm:"Cari Latihan Industri IT"}
},
{
  slug:"internship-perakaunan-accounting-2026",type:"internship",
  keywords:{primary:"accounting internship malaysia 2026",primary_bm:"latihan industri perakaunan malaysia 2026",
    longtail_en:["audit internship malaysia 2026","Big 4 internship malaysia","Deloitte PwC KPMG internship","accounting firm internship"],
    longtail_bm:["latihan industri audit malaysia 2026","latihan industri Big 4 malaysia","latihan industri Deloitte PwC KPMG","latihan industri firma perakaunan"]},
  meta:{title:"Accounting & Audit Internships Malaysia 2026 | MyScholar",title_bm:"Latihan Industri Perakaunan & Audit Malaysia 2026 | MyScholar",
    description:"Accounting internships in Malaysia 2026. Big 4 firms, local audit houses, and corporate finance.",
    description_bm:"Latihan industri perakaunan Malaysia 2026. Firma Big 4, firma audit tempatan, dan kewangan korporat."},
  landing:{h1_en:"Accounting Internships Malaysia 2026",h1_bm:"Latihan Industri Perakaunan 2026",
    intro_en:"From Big 4 firms to local audit houses, accounting internships are a critical career stepping stone.",
    intro_bm:"Dari firma Big 4 hingga firma audit tempatan, latihan industri perakaunan adalah batu loncatan kerjaya yang kritikal.",
    cta_en:"Browse Accounting Internships",cta_bm:"Layari Latihan Industri Perakaunan"}
}
];
