// JACK Wave 5 — MyTuition Launch Pages, Scholarship Partnerships, Internship Gaps
// Created: 2026-04-16
// ~55 entries across 3 categories:
//   1. TUITION (20) — new product launch; type="tuition" links to /tuition
//   2. SCHOLARSHIP PARTNERSHIPS + GAPS (15) — fill missing high-intent keywords
//   3. INTERNSHIP GAPS (20) — government agencies, media, pharma, remote, regions
module.exports = [

// ============================================================
// === TUITION — NEW PRODUCT LAUNCH (myscholar.my/tuition) ===
// ============================================================
// Note: type="tuition" will route these pages to /tuition directory
// Color: #b85c3a (terracotta — warm linen/MyTuition aesthetic)

{
  slug:"tuition-centre-kl-2026",type:"tuition",
  keywords:{primary:"tuition centre KL 2026",primary_bm:"pusat tuisyen KL 2026",
    longtail_en:["best tuition centre Kuala Lumpur 2026","tuition centre near me KL","SPM tuition KL 2026","affordable tuition KL","recommended tuition centre KL"],
    longtail_bm:["pusat tuisyen terbaik Kuala Lumpur 2026","pusat tuisyen berhampiran KL","tuisyen SPM KL 2026","tuisyen murah KL","pusat tuisyen disyorkan KL"]},
  meta:{title:"Tuition Centres in KL 2026 | MyTuition Malaysia",title_bm:"Pusat Tuisyen KL 2026 | MyTuition Malaysia",
    description:"Find the best tuition centres in Kuala Lumpur 2026. Compare SPM, IGCSE, and A-Level tuition centres by subject, area, and student reviews.",
    description_bm:"Cari pusat tuisyen terbaik di Kuala Lumpur 2026. Bandingkan pusat tuisyen SPM, IGCSE, dan A-Level mengikut subjek, kawasan, dan ulasan pelajar."},
  landing:{h1_en:"Find a Tuition Centre in KL 2026",h1_bm:"Cari Pusat Tuisyen di KL 2026",
    intro_en:"Finding the right tuition centre in KL is harder than it should be. MyTuition maps over 200+ tuition centres across Kuala Lumpur — filtered by subject, area, and student ratings. No paid listings. Just centres worth knowing about.",
    intro_bm:"Mencari pusat tuisyen yang sesuai di KL lebih sukar dari yang sepatutnya. MyTuition memetakan 200+ pusat tuisyen merentasi Kuala Lumpur — ditapis mengikut subjek, kawasan, dan penilaian pelajar. Tiada senarai berbayar. Hanya pusat yang patut diketahui.",
    cta_en:"Browse KL Tuition Centres",cta_bm:"Semak Pusat Tuisyen KL"}
},
{
  slug:"spm-tuition-centre-malaysia-2026",type:"tuition",
  keywords:{primary:"SPM tuition centre Malaysia 2026",primary_bm:"pusat tuisyen SPM Malaysia 2026",
    longtail_en:["SPM tuition near me Malaysia","Form 4 Form 5 tuition Malaysia","best SPM tuition centre 2026","SPM preparation tuition Malaysia","top SPM tutor Malaysia"],
    longtail_bm:["tuisyen SPM berdekatan saya Malaysia","tuisyen Tingkatan 4 Tingkatan 5 Malaysia","pusat tuisyen SPM terbaik 2026","tuisyen persediaan SPM Malaysia","tutor SPM terbaik Malaysia"]},
  meta:{title:"SPM Tuition Centre Malaysia 2026 | MyTuition",title_bm:"Pusat Tuisyen SPM Malaysia 2026 | MyTuition",
    description:"SPM tuition centres in Malaysia 2026. Find Form 4 and Form 5 tuition for all subjects — Maths, Science, BM, English, and more.",
    description_bm:"Pusat tuisyen SPM di Malaysia 2026. Cari tuisyen Tingkatan 4 dan 5 untuk semua subjek — Matematik, Sains, BM, Bahasa Inggeris, dan lain-lain."},
  landing:{h1_en:"SPM Tuition Centres Malaysia 2026",h1_bm:"Pusat Tuisyen SPM Malaysia 2026",
    intro_en:"SPM is the exam that defines your university and scholarship options. Finding the right tuition centre — for the right subject, at the right price — matters. MyTuition lists SPM tuition centres across Malaysia with real student reviews and subject coverage.",
    intro_bm:"SPM adalah peperiksaan yang menentukan pilihan universiti dan biasiswa anda. Mencari pusat tuisyen yang tepat — untuk subjek yang betul, pada harga yang sesuai — penting. MyTuition menyenaraikan pusat tuisyen SPM merentasi Malaysia dengan ulasan pelajar sebenar dan liputan subjek.",
    cta_en:"Find SPM Tuition Centres",cta_bm:"Cari Pusat Tuisyen SPM"}
},
{
  slug:"add-maths-tuition-kl-2026",type:"tuition",
  keywords:{primary:"Add Maths tuition KL 2026",primary_bm:"tuisyen Matematik Tambahan KL 2026",
    longtail_en:["Additional Mathematics tuition Kuala Lumpur","SPM Add Maths tutor KL","Form 5 Add Maths tuition Malaysia","best Add Maths tuition centre KL","A+ Add Maths tuition 2026"],
    longtail_bm:["tuisyen Matematik Tambahan Kuala Lumpur","tutor Add Maths SPM KL","tuisyen Add Maths Tingkatan 5 Malaysia","pusat tuisyen Matematik Tambahan terbaik KL","tuisyen A+ Add Maths 2026"]},
  meta:{title:"Add Maths Tuition KL 2026 | MyTuition Malaysia",title_bm:"Tuisyen Matematik Tambahan KL 2026 | MyTuition",
    description:"Find Additional Mathematics (Add Maths) tuition centres in KL 2026. SPM Form 4 & 5 specialist tutors in Kuala Lumpur and Klang Valley.",
    description_bm:"Cari pusat tuisyen Matematik Tambahan di KL 2026. Tutor pakar SPM Tingkatan 4 & 5 di Kuala Lumpur dan Lembah Klang."},
  landing:{h1_en:"Additional Maths Tuition in KL 2026",h1_bm:"Tuisyen Matematik Tambahan KL 2026",
    intro_en:"Add Maths is the subject most SPM students struggle with the most. The right tutor changes that. MyTuition lists Add Maths specialists across KL — sorted by student ratings, area, and whether they offer small group or 1-on-1 sessions.",
    intro_bm:"Matematik Tambahan adalah subjek yang paling ramai pelajar SPM hadapi masalah. Tutor yang betul mengubah itu. MyTuition menyenaraikan pakar Matematik Tambahan merentasi KL — disusun mengikut penilaian pelajar, kawasan, dan sama ada mereka menawarkan kumpulan kecil atau sesi 1-on-1.",
    cta_en:"Find Add Maths Tutors KL",cta_bm:"Cari Tutor Add Maths KL"}
},
{
  slug:"physics-tuition-kl-2026",type:"tuition",
  keywords:{primary:"Physics tuition KL 2026",primary_bm:"tuisyen Fizik KL 2026",
    longtail_en:["SPM Physics tuition Kuala Lumpur","Form 4 Physics tutor KL","best Physics tuition centre Malaysia","A-Level Physics tuition KL","IGCSE Physics tuition Malaysia"],
    longtail_bm:["tuisyen Fizik SPM Kuala Lumpur","tutor Fizik Tingkatan 4 KL","pusat tuisyen Fizik terbaik Malaysia","tuisyen Fizik A-Level KL","tuisyen Fizik IGCSE Malaysia"]},
  meta:{title:"Physics Tuition KL 2026 | MyTuition Malaysia",title_bm:"Tuisyen Fizik KL 2026 | MyTuition Malaysia",
    description:"Physics tuition centres in Kuala Lumpur 2026. SPM, IGCSE, and A-Level Physics tutors with verified student reviews.",
    description_bm:"Pusat tuisyen Fizik di Kuala Lumpur 2026. Tutor Fizik SPM, IGCSE, dan A-Level dengan ulasan pelajar yang disahkan."},
  landing:{h1_en:"Physics Tuition in KL 2026",h1_bm:"Tuisyen Fizik KL 2026",
    intro_en:"Physics is one of the trickiest SPM subjects — concepts build on each other and gaps compound fast. MyTuition lists Physics specialists in KL rated by actual students, covering SPM, IGCSE, and A-Level.",
    intro_bm:"Fizik adalah salah satu subjek SPM yang paling sukar — konsep bergantung antara satu sama lain dan jurang berkembang cepat. MyTuition menyenaraikan pakar Fizik di KL yang dinilai oleh pelajar sebenar, meliputi SPM, IGCSE, dan A-Level.",
    cta_en:"Find Physics Tutors KL",cta_bm:"Cari Tutor Fizik KL"}
},
{
  slug:"chemistry-tuition-kl-2026",type:"tuition",
  keywords:{primary:"Chemistry tuition KL 2026",primary_bm:"tuisyen Kimia KL 2026",
    longtail_en:["SPM Chemistry tuition Kuala Lumpur","Form 5 Chemistry tutor KL","best Chemistry tuition Malaysia","A-Level Chemistry tuition KL","IGCSE Chemistry tuition Malaysia"],
    longtail_bm:["tuisyen Kimia SPM Kuala Lumpur","tutor Kimia Tingkatan 5 KL","pusat tuisyen Kimia terbaik Malaysia","tuisyen Kimia A-Level KL","tuisyen Kimia IGCSE Malaysia"]},
  meta:{title:"Chemistry Tuition KL 2026 | MyTuition Malaysia",title_bm:"Tuisyen Kimia KL 2026 | MyTuition Malaysia",
    description:"Chemistry tuition centres in Kuala Lumpur 2026. SPM, IGCSE, and A-Level Chemistry tutors near you.",
    description_bm:"Pusat tuisyen Kimia di Kuala Lumpur 2026. Tutor Kimia SPM, IGCSE, dan A-Level berhampiran anda."},
  landing:{h1_en:"Chemistry Tuition in KL 2026",h1_bm:"Tuisyen Kimia KL 2026",
    intro_en:"Chemistry demands both memorisation and conceptual understanding — and the right tutor makes the difference. MyTuition maps Chemistry specialists across KL for SPM, IGCSE, and A-Level students.",
    intro_bm:"Kimia memerlukan hafalan dan pemahaman konseptual — dan tutor yang betul membuat perbezaan. MyTuition memetakan pakar Kimia merentasi KL untuk pelajar SPM, IGCSE, dan A-Level.",
    cta_en:"Find Chemistry Tutors KL",cta_bm:"Cari Tutor Kimia KL"}
},
{
  slug:"biology-tuition-kl-2026",type:"tuition",
  keywords:{primary:"Biology tuition KL 2026",primary_bm:"tuisyen Biologi KL 2026",
    longtail_en:["SPM Biology tuition Kuala Lumpur","Form 4 Biology tutor KL","best Biology tuition Malaysia","pre-med Biology tuition KL","IGCSE Biology tuition KL"],
    longtail_bm:["tuisyen Biologi SPM Kuala Lumpur","tutor Biologi Tingkatan 4 KL","pusat tuisyen Biologi terbaik Malaysia","tuisyen Biologi pra-perubatan KL","tuisyen Biologi IGCSE KL"]},
  meta:{title:"Biology Tuition KL 2026 | MyTuition Malaysia",title_bm:"Tuisyen Biologi KL 2026 | MyTuition Malaysia",
    description:"Biology tuition in Kuala Lumpur 2026. SPM and A-Level Biology tutors for students aiming for medicine, pharmacy, or science.",
    description_bm:"Tuisyen Biologi di Kuala Lumpur 2026. Tutor Biologi SPM dan A-Level untuk pelajar yang ingin mengambil perubatan, farmasi, atau sains."},
  landing:{h1_en:"Biology Tuition in KL 2026",h1_bm:"Tuisyen Biologi KL 2026",
    intro_en:"Biology is essential for students heading into medicine, pharmacy, or biotech. MyTuition lists Biology specialists in KL — covering SPM content and A-Level/IGCSE prep for competitive university entries.",
    intro_bm:"Biologi penting untuk pelajar yang menuju ke perubatan, farmasi, atau bioteknologi. MyTuition menyenaraikan pakar Biologi di KL — meliputi kandungan SPM dan persediaan A-Level/IGCSE untuk kemasukan universiti yang kompetitif.",
    cta_en:"Find Biology Tutors KL",cta_bm:"Cari Tutor Biologi KL"}
},
{
  slug:"english-tuition-kl-2026",type:"tuition",
  keywords:{primary:"English tuition KL 2026",primary_bm:"tuisyen Bahasa Inggeris KL 2026",
    longtail_en:["SPM English tuition Kuala Lumpur","English essay tuition KL","conversational English class KL","MUET English preparation KL","IELTS preparation tuition KL"],
    longtail_bm:["tuisyen Bahasa Inggeris SPM Kuala Lumpur","tuisyen karangan Inggeris KL","kelas perbualan Bahasa Inggeris KL","persediaan MUET Bahasa Inggeris KL","persediaan IELTS KL"]},
  meta:{title:"English Tuition KL 2026 | MyTuition Malaysia",title_bm:"Tuisyen Bahasa Inggeris KL 2026 | MyTuition",
    description:"English tuition in Kuala Lumpur 2026. SPM English, MUET preparation, and conversational English classes across KL and Klang Valley.",
    description_bm:"Tuisyen Bahasa Inggeris di Kuala Lumpur 2026. Bahasa Inggeris SPM, persediaan MUET, dan kelas perbualan Bahasa Inggeris merentasi KL dan Lembah Klang."},
  landing:{h1_en:"English Tuition in KL 2026",h1_bm:"Tuisyen Bahasa Inggeris KL 2026",
    intro_en:"English affects your SPM grade, your MUET band, and how confidently you interview for scholarships and jobs. MyTuition lists English tutors in KL for all levels — from SPM essay writing to MUET Band 5+.",
    intro_bm:"Bahasa Inggeris mempengaruhi gred SPM anda, band MUET anda, dan keyakinan anda untuk temuduga biasiswa dan kerja. MyTuition menyenaraikan tutor Bahasa Inggeris di KL untuk semua peringkat — daripada penulisan esei SPM hingga MUET Band 5+.",
    cta_en:"Find English Tutors KL",cta_bm:"Cari Tutor Bahasa Inggeris KL"}
},
{
  slug:"bahasa-malaysia-tuition-kl-2026",type:"tuition",
  keywords:{primary:"Bahasa Malaysia tuition KL 2026",primary_bm:"tuisyen Bahasa Melayu KL 2026",
    longtail_en:["BM tuition KL 2026","SPM Bahasa Melayu tuition Kuala Lumpur","BM essay tuition KL","Bahasa Malaysia tutor KL","karangan BM tuition Malaysia"],
    longtail_bm:["tuisyen BM KL 2026","tuisyen Bahasa Melayu SPM Kuala Lumpur","tuisyen karangan BM KL","tutor Bahasa Melayu KL","tuisyen karangan Bahasa Melayu Malaysia"]},
  meta:{title:"Bahasa Malaysia Tuition KL 2026 | MyTuition",title_bm:"Tuisyen Bahasa Melayu KL 2026 | MyTuition",
    description:"Bahasa Malaysia (BM) tuition in Kuala Lumpur 2026. SPM BM tutors specialising in karangan, komsas, and comprehension across KL.",
    description_bm:"Tuisyen Bahasa Malaysia (BM) di Kuala Lumpur 2026. Tutor BM SPM yang pakar dalam karangan, komsas, dan pemahaman merentasi KL."},
  landing:{h1_en:"Bahasa Malaysia Tuition in KL 2026",h1_bm:"Tuisyen Bahasa Melayu KL 2026",
    intro_en:"A+ in BM is required for some of the top scholarships in Malaysia — JPA in particular demands it. MyTuition lists BM specialists across KL, covering karangan, komsas, and reading comprehension.",
    intro_bm:"A+ dalam BM diperlukan untuk beberapa biasiswa terbaik di Malaysia — JPA khususnya memerlukannya. MyTuition menyenaraikan pakar BM merentasi KL, meliputi karangan, komsas, dan pemahaman bacaan.",
    cta_en:"Find BM Tutors KL",cta_bm:"Cari Tutor BM KL"}
},
{
  slug:"tuition-cheras-2026",type:"tuition",
  keywords:{primary:"tuition centre Cheras 2026",primary_bm:"pusat tuisyen Cheras 2026",
    longtail_en:["best tuition Cheras KL","SPM tuition Cheras","tuition near Cheras Batu 9","Cheras tutor 2026","tuition centre Taman Connaught"],
    longtail_bm:["tuisyen terbaik Cheras KL","tuisyen SPM Cheras","tuisyen berhampiran Cheras Batu 9","tutor Cheras 2026","pusat tuisyen Taman Connaught"]},
  meta:{title:"Tuition Centre Cheras 2026 | MyTuition Malaysia",title_bm:"Pusat Tuisyen Cheras 2026 | MyTuition Malaysia",
    description:"Tuition centres in Cheras, KL 2026. Find SPM and primary school tutors in Cheras, Taman Connaught, and surrounding areas.",
    description_bm:"Pusat tuisyen di Cheras, KL 2026. Cari tutor SPM dan sekolah rendah di Cheras, Taman Connaught, dan kawasan sekitarnya."},
  landing:{h1_en:"Tuition Centres in Cheras 2026",h1_bm:"Pusat Tuisyen Cheras 2026",
    intro_en:"Cheras is one of KL's most densely populated residential areas — and tuition demand here is high. MyTuition maps centres across Cheras, Batu 9, Taman Connaught, and Batu 11 with verified reviews.",
    intro_bm:"Cheras adalah salah satu kawasan kediaman yang paling padat di KL — dan permintaan tuisyen di sini tinggi. MyTuition memetakan pusat merentasi Cheras, Batu 9, Taman Connaught, dan Batu 11 dengan ulasan yang disahkan.",
    cta_en:"Find Tuition in Cheras",cta_bm:"Cari Tuisyen di Cheras"}
},
{
  slug:"tuition-petaling-jaya-2026",type:"tuition",
  keywords:{primary:"tuition centre Petaling Jaya 2026",primary_bm:"pusat tuisyen Petaling Jaya 2026",
    longtail_en:["best tuition PJ 2026","SPM tuition Petaling Jaya","tuition SS2 PJ","tuition Damansara PJ","tuition centre Section 17 PJ"],
    longtail_bm:["tuisyen terbaik PJ 2026","tuisyen SPM Petaling Jaya","tuisyen SS2 PJ","tuisyen Damansara PJ","pusat tuisyen Seksyen 17 PJ"]},
  meta:{title:"Tuition Centre Petaling Jaya 2026 | MyTuition",title_bm:"Pusat Tuisyen Petaling Jaya 2026 | MyTuition",
    description:"Tuition centres in Petaling Jaya 2026. SPM, IGCSE, and primary tuition in PJ — SS2, Damansara, Section 17, and more.",
    description_bm:"Pusat tuisyen di Petaling Jaya 2026. Tuisyen SPM, IGCSE, dan sekolah rendah di PJ — SS2, Damansara, Seksyen 17, dan lain-lain."},
  landing:{h1_en:"Tuition Centres in Petaling Jaya 2026",h1_bm:"Pusat Tuisyen Petaling Jaya 2026",
    intro_en:"PJ has some of the highest density of quality tuition centres in Malaysia. MyTuition maps options across SS2, Damansara Utama, Section 17, and Kelana Jaya — sorted by subject and student reviews.",
    intro_bm:"PJ mempunyai antara kepadatan tertinggi pusat tuisyen berkualiti di Malaysia. MyTuition memetakan pilihan merentasi SS2, Damansara Utama, Seksyen 17, dan Kelana Jaya — disusun mengikut subjek dan ulasan pelajar.",
    cta_en:"Find Tuition in PJ",cta_bm:"Cari Tuisyen di PJ"}
},
{
  slug:"tuition-subang-jaya-2026",type:"tuition",
  keywords:{primary:"tuition centre Subang Jaya 2026",primary_bm:"pusat tuisyen Subang Jaya 2026",
    longtail_en:["best tuition Subang Jaya","SPM tuition Subang 2026","tuition USJ Subang","tuition Subang Parade area","IGCSE tuition Subang Jaya"],
    longtail_bm:["tuisyen terbaik Subang Jaya","tuisyen SPM Subang 2026","tuisyen USJ Subang","tuisyen kawasan Subang Parade","tuisyen IGCSE Subang Jaya"]},
  meta:{title:"Tuition Centre Subang Jaya 2026 | MyTuition",title_bm:"Pusat Tuisyen Subang Jaya 2026 | MyTuition",
    description:"Tuition centres in Subang Jaya 2026. SPM and IGCSE tutors in USJ, Subang Jaya, and the SS15 corridor.",
    description_bm:"Pusat tuisyen di Subang Jaya 2026. Tutor SPM dan IGCSE di USJ, Subang Jaya, dan koridor SS15."},
  landing:{h1_en:"Tuition Centres in Subang Jaya 2026",h1_bm:"Pusat Tuisyen Subang Jaya 2026",
    intro_en:"Subang Jaya's student population is large — SJK, national schools, and international schools all feeding into the same tuition demand. MyTuition maps centres across USJ, SS15, and the Subang corridor.",
    intro_bm:"Populasi pelajar Subang Jaya adalah besar — SJK, sekolah kebangsaan, dan sekolah antarabangsa semua menyumbang kepada permintaan tuisyen yang sama. MyTuition memetakan pusat merentasi USJ, SS15, dan koridor Subang.",
    cta_en:"Find Tuition in Subang Jaya",cta_bm:"Cari Tuisyen di Subang Jaya"}
},
{
  slug:"tuition-wangsa-maju-2026",type:"tuition",
  keywords:{primary:"tuition centre Wangsa Maju 2026",primary_bm:"pusat tuisyen Wangsa Maju 2026",
    longtail_en:["SPM tuition Wangsa Maju KL","tuition near AEON Wangsa Maju","tuition Setapak 2026","tuition centre Wangsa Walk","Keramat tuition centre"],
    longtail_bm:["tuisyen SPM Wangsa Maju KL","tuisyen berdekatan AEON Wangsa Maju","tuisyen Setapak 2026","pusat tuisyen Wangsa Walk","pusat tuisyen Keramat"]},
  meta:{title:"Tuition Centre Wangsa Maju 2026 | MyTuition",title_bm:"Pusat Tuisyen Wangsa Maju 2026 | MyTuition",
    description:"Tuition centres in Wangsa Maju, Setapak, and Keramat 2026. SPM and primary tuition centres in north-east KL.",
    description_bm:"Pusat tuisyen di Wangsa Maju, Setapak, dan Keramat 2026. Pusat tuisyen SPM dan sekolah rendah di timur laut KL."},
  landing:{h1_en:"Tuition Centres in Wangsa Maju 2026",h1_bm:"Pusat Tuisyen Wangsa Maju 2026",
    intro_en:"Wangsa Maju and Setapak have a dense school catchment — lots of SPM students, fewer well-mapped tuition options. MyTuition fills that gap with verified centres in Wangsa Maju, Keramat, and Setapak.",
    intro_bm:"Wangsa Maju dan Setapak mempunyai kawasan sekolah yang padat — ramai pelajar SPM, tetapi pilihan tuisyen yang dipetakan kurang baik. MyTuition mengisi jurang itu dengan pusat tuisyen yang disahkan di Wangsa Maju, Keramat, dan Setapak.",
    cta_en:"Find Tuition in Wangsa Maju",cta_bm:"Cari Tuisyen di Wangsa Maju"}
},
{
  slug:"tuition-puchong-2026",type:"tuition",
  keywords:{primary:"tuition centre Puchong 2026",primary_bm:"pusat tuisyen Puchong 2026",
    longtail_en:["SPM tuition Puchong Selangor","best tuition Puchong Jaya","tuition IOI Puchong","IGCSE tuition Puchong","tuition centre Bandar Puchong Jaya"],
    longtail_bm:["tuisyen SPM Puchong Selangor","tuisyen terbaik Puchong Jaya","tuisyen IOI Puchong","tuisyen IGCSE Puchong","pusat tuisyen Bandar Puchong Jaya"]},
  meta:{title:"Tuition Centre Puchong 2026 | MyTuition Malaysia",title_bm:"Pusat Tuisyen Puchong 2026 | MyTuition Malaysia",
    description:"Tuition centres in Puchong 2026. SPM and IGCSE tuition in Puchong Jaya, Bandar Puchong, and IOI Mall area.",
    description_bm:"Pusat tuisyen di Puchong 2026. Tuisyen SPM dan IGCSE di Puchong Jaya, Bandar Puchong, dan kawasan IOI Mall."},
  landing:{h1_en:"Tuition Centres in Puchong 2026",h1_bm:"Pusat Tuisyen Puchong 2026",
    intro_en:"Puchong is one of Selangor's most rapidly growing residential areas — and tuition demand has grown with it. MyTuition maps centres across Puchong Jaya, Puteri, and IOI with verified student reviews.",
    intro_bm:"Puchong adalah salah satu kawasan kediaman yang berkembang paling pesat di Selangor — dan permintaan tuisyen telah berkembang bersamanya. MyTuition memetakan pusat merentasi Puchong Jaya, Puteri, dan IOI dengan ulasan pelajar yang disahkan.",
    cta_en:"Find Tuition in Puchong",cta_bm:"Cari Tuisyen di Puchong"}
},
{
  slug:"best-tuition-centre-malaysia-2026",type:"tuition",
  keywords:{primary:"best tuition centre Malaysia 2026",primary_bm:"pusat tuisyen terbaik Malaysia 2026",
    longtail_en:["top rated tuition Malaysia 2026","most recommended tuition centre Malaysia","award winning tuition Malaysia","highly rated tutor Malaysia 2026","trusted tuition centre Malaysia"],
    longtail_bm:["tuisyen tertinggi rating Malaysia 2026","pusat tuisyen paling disyorkan Malaysia","pusat tuisyen anugerah Malaysia","tutor amat disyorkan Malaysia 2026","pusat tuisyen dipercayai Malaysia"]},
  meta:{title:"Best Tuition Centres Malaysia 2026 | MyTuition",title_bm:"Pusat Tuisyen Terbaik Malaysia 2026 | MyTuition",
    description:"Best tuition centres in Malaysia 2026 — ranked by student reviews, subject coverage, and verified results. No paid rankings.",
    description_bm:"Pusat tuisyen terbaik di Malaysia 2026 — diranking mengikut ulasan pelajar, liputan subjek, dan keputusan yang disahkan. Tiada ranking berbayar."},
  landing:{h1_en:"Best Tuition Centres in Malaysia 2026",h1_bm:"Pusat Tuisyen Terbaik Malaysia 2026",
    intro_en:"'Best tuition centre' lists on most sites are paid placements. MyTuition ranks differently — centres are listed based on student reviews, subject depth, and whether their data is verified and current. Still early days, but already worth browsing.",
    intro_bm:"Senarai 'pusat tuisyen terbaik' di kebanyakan laman adalah penempatan berbayar. MyTuition meranking secara berbeza — pusat disenaraikan berdasarkan ulasan pelajar, kedalaman subjek, dan sama ada data mereka disahkan dan terkini. Masih awal, tetapi sudah patut dilayari.",
    cta_en:"Browse Top Tuition Centres",cta_bm:"Semak Pusat Tuisyen Terbaik"}
},
{
  slug:"online-tuition-spm-malaysia-2026",type:"tuition",
  keywords:{primary:"online tuition SPM Malaysia 2026",primary_bm:"tuisyen online SPM Malaysia 2026",
    longtail_en:["online tutor SPM Malaysia 2026","virtual tuition Malaysia","online tuition Zoom Malaysia","best online SPM tutor Malaysia","remote tuition Malaysia 2026"],
    longtail_bm:["tutor online SPM Malaysia 2026","tuisyen maya Malaysia","tuisyen online Zoom Malaysia","tutor SPM online terbaik Malaysia","tuisyen jarak jauh Malaysia 2026"]},
  meta:{title:"Online SPM Tuition Malaysia 2026 | MyTuition",title_bm:"Tuisyen Online SPM Malaysia 2026 | MyTuition",
    description:"Online SPM tuition in Malaysia 2026. Find virtual tutors for Add Maths, Physics, Chemistry, and all SPM subjects from anywhere in Malaysia.",
    description_bm:"Tuisyen SPM online di Malaysia 2026. Cari tutor maya untuk Matematik Tambahan, Fizik, Kimia, dan semua subjek SPM dari mana sahaja di Malaysia."},
  landing:{h1_en:"Online SPM Tuition Malaysia 2026",h1_bm:"Tuisyen Online SPM Malaysia 2026",
    intro_en:"Online tuition removed the location constraint — a student in Kelantan can access the best Add Maths tutor in PJ. MyTuition lists online-capable tutors for all SPM subjects, including ratings and subject specialisation.",
    intro_bm:"Tuisyen online menghilangkan kekangan lokasi — pelajar di Kelantan boleh mengakses tutor Matematik Tambahan terbaik di PJ. MyTuition menyenaraikan tutor berkemampuan online untuk semua subjek SPM, termasuk penilaian dan pengkhususan subjek.",
    cta_en:"Find Online SPM Tutors",cta_bm:"Cari Tutor SPM Online"}
},
{
  slug:"home-tutor-kl-spm-2026",type:"tuition",
  keywords:{primary:"home tutor KL SPM 2026",primary_bm:"tutor peribadi KL SPM 2026",
    longtail_en:["private tutor Kuala Lumpur 2026","home tutoring SPM KL","1-on-1 tutor KL Malaysia","personal tutor SPM Malaysia","home visit tutor KL 2026"],
    longtail_bm:["tutor swasta Kuala Lumpur 2026","tuisyen rumah SPM KL","tutor 1-on-1 KL Malaysia","tutor peribadi SPM Malaysia","tutor lawatan rumah KL 2026"]},
  meta:{title:"Home Tutor KL 2026 | MyTuition Malaysia",title_bm:"Tutor Peribadi KL 2026 | MyTuition Malaysia",
    description:"Home tutors in Kuala Lumpur 2026. Find 1-on-1 and private SPM tutors who come to your home across KL and Klang Valley.",
    description_bm:"Tutor peribadi di Kuala Lumpur 2026. Cari tutor SPM 1-on-1 dan swasta yang datang ke rumah anda merentasi KL dan Lembah Klang."},
  landing:{h1_en:"Home Tutors in KL 2026",h1_bm:"Tutor Peribadi KL 2026",
    intro_en:"Some students learn best 1-on-1 at home — no commute, focused pace, personalised content. MyTuition lists home tutors in KL who offer in-person sessions, with verified availability and subject coverage.",
    intro_bm:"Sesetengah pelajar belajar paling baik secara 1-on-1 di rumah — tiada perjalanan, kadar terfokus, kandungan diperibadikan. MyTuition menyenaraikan tutor rumah di KL yang menawarkan sesi bersemuka, dengan ketersediaan yang disahkan dan liputan subjek.",
    cta_en:"Find a Home Tutor in KL",cta_bm:"Cari Tutor Peribadi di KL"}
},
{
  slug:"igcse-tuition-kl-2026",type:"tuition",
  keywords:{primary:"IGCSE tuition KL 2026",primary_bm:"tuisyen IGCSE KL 2026",
    longtail_en:["IGCSE tuition centre Kuala Lumpur 2026","Cambridge IGCSE tutor KL","IGCSE Maths tuition KL","IGCSE Science tuition KL","international school tuition KL"],
    longtail_bm:["pusat tuisyen IGCSE Kuala Lumpur 2026","tutor Cambridge IGCSE KL","tuisyen Matematik IGCSE KL","tuisyen Sains IGCSE KL","tuisyen sekolah antarabangsa KL"]},
  meta:{title:"IGCSE Tuition KL 2026 | MyTuition Malaysia",title_bm:"Tuisyen IGCSE KL 2026 | MyTuition Malaysia",
    description:"IGCSE tuition centres in Kuala Lumpur 2026. Cambridge-trained tutors for Maths, Sciences, English, and Humanities.",
    description_bm:"Pusat tuisyen IGCSE di Kuala Lumpur 2026. Tutor terlatih Cambridge untuk Matematik, Sains, Bahasa Inggeris, dan Kemanusiaan."},
  landing:{h1_en:"IGCSE Tuition in KL 2026",h1_bm:"Tuisyen IGCSE KL 2026",
    intro_en:"IGCSE students in KL are increasingly choosing specialist tuition over general centres. MyTuition maps IGCSE-experienced tutors across KL — categorised by subject, Cambridge or Edexcel board, and student ratings.",
    intro_bm:"Pelajar IGCSE di KL semakin memilih tuisyen pakar berbanding pusat umum. MyTuition memetakan tutor berpengalaman IGCSE merentasi KL — dikategorikan mengikut subjek, papan Cambridge atau Edexcel, dan penilaian pelajar.",
    cta_en:"Find IGCSE Tutors KL",cta_bm:"Cari Tutor IGCSE KL"}
},
{
  slug:"tuition-ampang-2026",type:"tuition",
  keywords:{primary:"tuition centre Ampang 2026",primary_bm:"pusat tuisyen Ampang 2026",
    longtail_en:["SPM tuition Ampang KL","best tuition Ampang Jaya","tuition Ukay Perdana","tuition centre Taman Cahaya Ampang","Ampang tutor 2026"],
    longtail_bm:["tuisyen SPM Ampang KL","tuisyen terbaik Ampang Jaya","tuisyen Ukay Perdana","pusat tuisyen Taman Cahaya Ampang","tutor Ampang 2026"]},
  meta:{title:"Tuition Centre Ampang 2026 | MyTuition Malaysia",title_bm:"Pusat Tuisyen Ampang 2026 | MyTuition Malaysia",
    description:"Tuition centres in Ampang and Ampang Jaya 2026. Find SPM, primary, and IGCSE tuition near you in the Ampang corridor.",
    description_bm:"Pusat tuisyen di Ampang dan Ampang Jaya 2026. Cari tuisyen SPM, sekolah rendah, dan IGCSE berdekatan anda di koridor Ampang."},
  landing:{h1_en:"Tuition Centres in Ampang 2026",h1_bm:"Pusat Tuisyen Ampang 2026",
    intro_en:"Ampang and Ampang Jaya have a growing residential population with limited well-reviewed tuition options listed online. MyTuition fills that gap — covering Taman Cahaya, Ukay Perdana, and central Ampang.",
    intro_bm:"Ampang dan Ampang Jaya mempunyai populasi kediaman yang berkembang dengan pilihan tuisyen yang disenaraikan dalam talian yang terhad. MyTuition mengisi jurang itu — meliputi Taman Cahaya, Ukay Perdana, dan Ampang tengah.",
    cta_en:"Find Tuition in Ampang",cta_bm:"Cari Tuisyen di Ampang"}
},
{
  slug:"alevel-tuition-kl-2026",type:"tuition",
  keywords:{primary:"A-Level tuition KL 2026",primary_bm:"tuisyen A-Level KL 2026",
    longtail_en:["A-Level tuition centre Kuala Lumpur","A-Level Maths tutor KL","A-Level Chemistry tuition KL","Cambridge A-Level tuition Malaysia","pre-university tuition KL"],
    longtail_bm:["pusat tuisyen A-Level Kuala Lumpur","tutor Matematik A-Level KL","tuisyen Kimia A-Level KL","tuisyen Cambridge A-Level Malaysia","tuisyen pra-universiti KL"]},
  meta:{title:"A-Level Tuition KL 2026 | MyTuition Malaysia",title_bm:"Tuisyen A-Level KL 2026 | MyTuition Malaysia",
    description:"A-Level tuition centres in Kuala Lumpur 2026. Cambridge A-Level specialist tutors for Maths, Sciences, Economics, and more.",
    description_bm:"Pusat tuisyen A-Level di Kuala Lumpur 2026. Tutor pakar Cambridge A-Level untuk Matematik, Sains, Ekonomi, dan lain-lain."},
  landing:{h1_en:"A-Level Tuition in KL 2026",h1_bm:"Tuisyen A-Level KL 2026",
    intro_en:"A-Level is high stakes — it's the qualification that determines your university options locally and abroad. MyTuition maps A-Level specialist tutors in KL, covering all subjects and both Cambridge and Edexcel.",
    intro_bm:"A-Level adalah pertaruhan tinggi — ia adalah kelayakan yang menentukan pilihan universiti anda di dalam dan luar negara. MyTuition memetakan tutor pakar A-Level di KL, meliputi semua subjek dan kedua-dua Cambridge dan Edexcel.",
    cta_en:"Find A-Level Tutors KL",cta_bm:"Cari Tutor A-Level KL"}
},

// ============================================================
// === SCHOLARSHIP PARTNERSHIPS + STRATEGIC GAPS ===
// ============================================================

{
  slug:"scholarship-for-engineering-students-malaysia-2026",type:"scholarship",
  keywords:{primary:"scholarship for engineering students Malaysia 2026",primary_bm:"biasiswa pelajar kejuruteraan Malaysia 2026",
    longtail_en:["engineering scholarship Malaysia 2026","petrochemical engineering scholarship Malaysia","civil engineering scholarship Malaysia 2026","electrical engineering scholarship 2026","mechanical engineering scholarship Malaysia"],
    longtail_bm:["biasiswa kejuruteraan Malaysia 2026","biasiswa kejuruteraan petrokimia Malaysia","biasiswa kejuruteraan awam Malaysia 2026","biasiswa kejuruteraan elektrik 2026","biasiswa kejuruteraan mekanikal Malaysia"]},
  meta:{title:"Engineering Scholarship Malaysia 2026 | MyScholar",title_bm:"Biasiswa Kejuruteraan Malaysia 2026 | MyScholar",
    description:"Scholarships for engineering students in Malaysia 2026. Civil, electrical, mechanical, chemical, and petroleum engineering awards.",
    description_bm:"Biasiswa untuk pelajar kejuruteraan di Malaysia 2026. Anugerah kejuruteraan awam, elektrik, mekanikal, kimia, dan petroleum."},
  landing:{h1_en:"Engineering Scholarships in Malaysia 2026",h1_bm:"Biasiswa Kejuruteraan Malaysia 2026",
    intro_en:"Engineering is one of the most-sponsored fields in Malaysia — Petronas, TNB, Sime Darby, and government bodies all prioritise engineering scholars. Browse MyScholar to find scholarships filtered for your engineering discipline.",
    intro_bm:"Kejuruteraan adalah salah satu bidang yang paling banyak ditaja di Malaysia — Petronas, TNB, Sime Darby, dan badan kerajaan semua mengutamakan pelajar kejuruteraan. Semak MyScholar untuk mencari biasiswa yang ditapis untuk disiplin kejuruteraan anda.",
    cta_en:"Browse Engineering Scholarships",cta_bm:"Semak Biasiswa Kejuruteraan"}
},
{
  slug:"scholarship-for-medical-students-malaysia-2026",type:"scholarship",
  keywords:{primary:"scholarship for medical students Malaysia 2026",primary_bm:"biasiswa pelajar perubatan Malaysia 2026",
    longtail_en:["MBBS scholarship Malaysia 2026","medical degree scholarship Malaysia","scholarship for doctor Malaysia","JPA medical scholarship Malaysia","Petronas medical scholarship"],
    longtail_bm:["biasiswa MBBS Malaysia 2026","biasiswa ijazah perubatan Malaysia","biasiswa untuk doktor Malaysia","biasiswa JPA perubatan Malaysia","biasiswa perubatan Petronas"]},
  meta:{title:"Medical Scholarship Malaysia 2026 | MyScholar",title_bm:"Biasiswa Perubatan Malaysia 2026 | MyScholar",
    description:"Scholarships for medical (MBBS) students in Malaysia 2026. Government, GLC, and foundation awards for aspiring doctors.",
    description_bm:"Biasiswa untuk pelajar perubatan (MBBS) di Malaysia 2026. Anugerah kerajaan, GLC, dan yayasan untuk doktor yang bercita-cita."},
  landing:{h1_en:"Medical Scholarships in Malaysia 2026",h1_bm:"Biasiswa Perubatan Malaysia 2026",
    intro_en:"Medicine is one of the most expensive and competitive degrees in Malaysia — and one of the most scholarship-supported. JPA, MARA, Petronas, and several private foundations all sponsor medical students. Browse the full list on MyScholar.",
    intro_bm:"Perubatan adalah salah satu ijazah yang paling mahal dan kompetitif di Malaysia — dan salah satu yang paling disokong biasiswa. JPA, MARA, Petronas, dan beberapa yayasan swasta semua menaja pelajar perubatan. Semak senarai penuh di MyScholar.",
    cta_en:"Browse Medical Scholarships",cta_bm:"Semak Biasiswa Perubatan"}
},
{
  slug:"scholarship-for-nursing-students-malaysia-2026",type:"scholarship",
  keywords:{primary:"scholarship for nursing students Malaysia 2026",primary_bm:"biasiswa pelajar kejururawatan Malaysia 2026",
    longtail_en:["nursing scholarship Malaysia 2026","KKM nursing scholarship Malaysia","MOH nursing scholarship 2026","scholarship for diploma nursing Malaysia","nursing degree scholarship Malaysia"],
    longtail_bm:["biasiswa kejururawatan Malaysia 2026","biasiswa kejururawatan KKM Malaysia","biasiswa kejururawatan KKM 2026","biasiswa diploma kejururawatan Malaysia","biasiswa ijazah kejururawatan Malaysia"]},
  meta:{title:"Nursing Scholarship Malaysia 2026 | MyScholar",title_bm:"Biasiswa Kejururawatan Malaysia 2026 | MyScholar",
    description:"Scholarships for nursing students in Malaysia 2026. Ministry of Health (KKM) and private hospital nursing awards.",
    description_bm:"Biasiswa untuk pelajar kejururawatan di Malaysia 2026. Anugerah kejururawatan Kementerian Kesihatan (KKM) dan hospital swasta."},
  landing:{h1_en:"Nursing Scholarships in Malaysia 2026",h1_bm:"Biasiswa Kejururawatan Malaysia 2026",
    intro_en:"Nursing is one of Malaysia's most needed healthcare professions — and there are scholarship options specifically for nursing students through the Ministry of Health and private hospital foundations. Browse MyScholar to see what's available.",
    intro_bm:"Kejururawatan adalah salah satu profesion penjagaan kesihatan yang paling diperlukan di Malaysia — dan terdapat pilihan biasiswa khusus untuk pelajar kejururawatan melalui Kementerian Kesihatan dan yayasan hospital swasta. Semak MyScholar untuk melihat apa yang tersedia.",
    cta_en:"Browse Nursing Scholarships",cta_bm:"Semak Biasiswa Kejururawatan"}
},
{
  slug:"biasiswa-penuh-malaysia-2026",type:"scholarship",
  keywords:{primary:"fully funded scholarship Malaysia 2026",primary_bm:"biasiswa penuh Malaysia 2026",
    longtail_en:["full scholarship Malaysia 2026","scholarship covering everything Malaysia","all expenses paid scholarship Malaysia","scholarship with living allowance Malaysia","100% scholarship Malaysia 2026"],
    longtail_bm:["biasiswa penuh Malaysia 2026","biasiswa tanpa perlu bayar balik Malaysia","biasiswa semua perbelanjaan Malaysia","biasiswa dengan elaun sara hidup Malaysia","biasiswa 100% Malaysia 2026"]},
  meta:{title:"Fully Funded Scholarships Malaysia 2026 | MyScholar",title_bm:"Biasiswa Penuh Malaysia 2026 | MyScholar",
    description:"Fully funded scholarships in Malaysia 2026. Awards covering tuition, living allowance, books, and flights — no partial funding.",
    description_bm:"Biasiswa penuh di Malaysia 2026. Anugerah meliputi yuran pengajian, elaun sara hidup, buku, dan tiket penerbangan — tiada pembiayaan separa."},
  landing:{h1_en:"Fully Funded Scholarships in Malaysia 2026",h1_bm:"Biasiswa Penuh Malaysia 2026",
    intro_en:"A fully funded scholarship covers tuition, accommodation, living expenses, and sometimes flights. In Malaysia, JPA PIDN, Yayasan Khazanah, Petronas, and some state foundations offer this — but most students don't know exactly which ones. MyScholar lists them clearly.",
    intro_bm:"Biasiswa penuh merangkumi yuran pengajian, penginapan, perbelanjaan sara hidup, dan kadang-kadang tiket penerbangan. Di Malaysia, JPA PIDN, Yayasan Khazanah, Petronas, dan beberapa yayasan negeri menawarkan ini — tetapi kebanyakan pelajar tidak tahu mana satu. MyScholar menyenaraikannya dengan jelas.",
    cta_en:"Find Fully Funded Scholarships",cta_bm:"Cari Biasiswa Penuh"}
},
{
  slug:"ptptn-vs-scholarship-malaysia-2026",type:"scholarship",
  keywords:{primary:"PTPTN vs scholarship Malaysia 2026",primary_bm:"PTPTN berbanding biasiswa Malaysia 2026",
    longtail_en:["should I apply PTPTN or scholarship Malaysia","PTPTN loan scholarship difference","scholarship better than PTPTN Malaysia","PTPTN interest rate comparison scholarship","can I get scholarship and PTPTN Malaysia"],
    longtail_bm:["patut mohon PTPTN atau biasiswa Malaysia","perbezaan pinjaman PTPTN dan biasiswa","biasiswa lebih baik dari PTPTN Malaysia","perbandingan kadar faedah PTPTN biasiswa","boleh dapat biasiswa dan PTPTN Malaysia"]},
  meta:{title:"PTPTN vs Scholarship Malaysia 2026 | MyScholar",title_bm:"PTPTN vs Biasiswa Malaysia 2026 | MyScholar",
    description:"PTPTN loan vs scholarship Malaysia — key differences, which is better, and whether you can apply for both at the same time.",
    description_bm:"Pinjaman PTPTN vs biasiswa Malaysia — perbezaan utama, mana yang lebih baik, dan sama ada anda boleh memohon kedua-duanya pada masa yang sama."},
  landing:{h1_en:"PTPTN vs Scholarship: What's the Difference?",h1_bm:"PTPTN vs Biasiswa: Apa Bezanya?",
    intro_en:"PTPTN is a loan — you pay it back (with conditions). A scholarship is a grant — no repayment. Many students don't realise you can often apply for both simultaneously, and that some scholarships cancel your PTPTN balance. MyScholar helps you understand the options.",
    intro_bm:"PTPTN adalah pinjaman — anda membayar balik (dengan syarat). Biasiswa adalah geran — tiada pembayaran balik. Ramai pelajar tidak sedar anda sering boleh memohon kedua-duanya serentak, dan sesetengah biasiswa membatalkan baki PTPTN anda. MyScholar membantu anda memahami pilihan.",
    cta_en:"Browse Scholarships vs PTPTN",cta_bm:"Semak Biasiswa vs PTPTN"}
},
{
  slug:"scholarship-bond-free-malaysia-2026",type:"scholarship",
  keywords:{primary:"scholarship no bond Malaysia 2026",primary_bm:"biasiswa tanpa ikatan Malaysia 2026",
    longtail_en:["scholarship without bond Malaysia 2026","no service bond scholarship Malaysia","free scholarship no payback Malaysia","scholarship without obligation Malaysia","merit scholarship no bond Malaysia 2026"],
    longtail_bm:["biasiswa tanpa ikatan Malaysia 2026","biasiswa tanpa ikatan perkhidmatan Malaysia","biasiswa percuma tanpa bayar balik Malaysia","biasiswa tanpa obligasi Malaysia","biasiswa merit tanpa ikatan Malaysia 2026"]},
  meta:{title:"Scholarships With No Bond Malaysia 2026 | MyScholar",title_bm:"Biasiswa Tanpa Ikatan Malaysia 2026 | MyScholar",
    description:"Scholarships in Malaysia 2026 with no service bond or payback obligation. Merit-based grants where you keep your options open after graduating.",
    description_bm:"Biasiswa di Malaysia 2026 tanpa ikatan perkhidmatan atau obligasi bayar balik. Geran berasaskan merit di mana anda mengekalkan pilihan selepas tamat pengajian."},
  landing:{h1_en:"Scholarships With No Bond in Malaysia 2026",h1_bm:"Biasiswa Tanpa Ikatan Malaysia 2026",
    intro_en:"Some of the best scholarships in Malaysia come with a service bond — you work for the sponsor after graduating. Others don't. If you want flexibility after university, there are bond-free options. MyScholar filters these for you.",
    intro_bm:"Sesetengah biasiswa terbaik di Malaysia datang dengan ikatan perkhidmatan — anda bekerja untuk penaja selepas tamat pengajian. Yang lain tidak. Jika anda mahukan fleksibiliti selepas universiti, terdapat pilihan tanpa ikatan. MyScholar menapis ini untuk anda.",
    cta_en:"Find Bond-Free Scholarships",cta_bm:"Cari Biasiswa Tanpa Ikatan"}
},
{
  slug:"corporate-scholarship-programme-malaysia-2026",type:"scholarship",
  keywords:{primary:"corporate scholarship programme Malaysia 2026",primary_bm:"program biasiswa korporat Malaysia 2026",
    longtail_en:["how to set up scholarship Malaysia","company scholarship programme Malaysia","CSR scholarship Malaysia 2026","corporate sponsorship student Malaysia","employer scholarship Malaysia"],
    longtail_bm:["cara buat biasiswa syarikat Malaysia","program biasiswa syarikat Malaysia","biasiswa CSR Malaysia 2026","tajaan korporat pelajar Malaysia","biasiswa majikan Malaysia"]},
  meta:{title:"Corporate Scholarship Programmes Malaysia 2026 | MyScholar",title_bm:"Program Biasiswa Korporat Malaysia 2026 | MyScholar",
    description:"Corporate scholarship programmes in Malaysia 2026. How companies set up student sponsorships, and where to list your scholarship for maximum student reach.",
    description_bm:"Program biasiswa korporat di Malaysia 2026. Cara syarikat menubuhkan tajaan pelajar, dan di mana menyenaraikan biasiswa anda untuk liputan pelajar maksimum."},
  landing:{h1_en:"Corporate Scholarship Programmes Malaysia 2026",h1_bm:"Program Biasiswa Korporat Malaysia 2026",
    intro_en:"Malaysia's best corporate scholarships — Petronas, Maybank, YTL, Shell — are run by companies that invested in the process. If you're a scholarship provider looking to reach the right students, listing on MyScholar puts you in front of 10,000+ student searches monthly.",
    intro_bm:"Biasiswa korporat terbaik Malaysia — Petronas, Maybank, YTL, Shell — dijalankan oleh syarikat yang melabur dalam prosesnya. Jika anda adalah penyedia biasiswa yang ingin menjangkau pelajar yang tepat, penyenaraian di MyScholar meletakkan anda di hadapan 10,000+ carian pelajar setiap bulan.",
    cta_en:"List Your Scholarship",cta_bm:"Senaraikan Biasiswa Anda"}
},
{
  slug:"scholarship-after-foundation-malaysia-2026",type:"scholarship",
  keywords:{primary:"scholarship after foundation Malaysia 2026",primary_bm:"biasiswa selepas asasi Malaysia 2026",
    longtail_en:["scholarship for foundation students Malaysia","post-foundation scholarship Malaysia","scholarship from foundation to degree Malaysia","UiTM foundation scholarship 2026","foundation year scholarship Malaysia"],
    longtail_bm:["biasiswa untuk pelajar asasi Malaysia","biasiswa selepas asasi Malaysia","biasiswa dari asasi ke ijazah Malaysia","biasiswa asasi UiTM 2026","biasiswa tahun asasi Malaysia"]},
  meta:{title:"Scholarships After Foundation Malaysia 2026 | MyScholar",title_bm:"Biasiswa Selepas Asasi Malaysia 2026 | MyScholar",
    description:"Scholarships for foundation students progressing to a degree in Malaysia 2026. Awards open to A-Level, STPM, and foundation year completers.",
    description_bm:"Biasiswa untuk pelajar asasi yang melanjutkan ke ijazah di Malaysia 2026. Anugerah terbuka untuk pelengkap A-Level, STPM, dan tahun asasi."},
  landing:{h1_en:"Scholarships After Foundation Malaysia 2026",h1_bm:"Biasiswa Selepas Asasi Malaysia 2026",
    intro_en:"Foundation-year completers have more scholarship options than most people think. MARA, certain private foundations, and some corporate sponsors specifically target students transitioning from foundation to degree. Browse MyScholar for the right ones.",
    intro_bm:"Pelengkap tahun asasi mempunyai lebih banyak pilihan biasiswa daripada yang kebanyakan orang fikir. MARA, yayasan swasta tertentu, dan beberapa penaja korporat khusus menyasarkan pelajar yang beralih dari asasi ke ijazah. Semak MyScholar untuk yang sesuai.",
    cta_en:"Browse Post-Foundation Scholarships",cta_bm:"Semak Biasiswa Selepas Asasi"}
},
{
  slug:"scholarship-for-private-university-malaysia-2026",type:"scholarship",
  keywords:{primary:"scholarship for private university Malaysia 2026",primary_bm:"biasiswa universiti swasta Malaysia 2026",
    longtail_en:["private university scholarship Malaysia 2026","Sunway scholarship 2026","Taylor's scholarship Malaysia","Monash scholarship Malaysia","HELP scholarship Malaysia 2026"],
    longtail_bm:["biasiswa universiti swasta Malaysia 2026","biasiswa Sunway 2026","biasiswa Taylor's Malaysia","biasiswa Monash Malaysia","biasiswa HELP Malaysia 2026"]},
  meta:{title:"Private University Scholarships Malaysia 2026 | MyScholar",title_bm:"Biasiswa Universiti Swasta Malaysia 2026 | MyScholar",
    description:"Scholarships for private universities in Malaysia 2026. Sunway, Taylor's, Monash, and HELP scholarship awards — merit and need-based.",
    description_bm:"Biasiswa untuk universiti swasta di Malaysia 2026. Anugerah biasiswa Sunway, Taylor's, Monash, dan HELP — berasaskan merit dan keperluan."},
  landing:{h1_en:"Private University Scholarships Malaysia 2026",h1_bm:"Biasiswa Universiti Swasta Malaysia 2026",
    intro_en:"Private universities in Malaysia offer some of the most accessible merit scholarships — especially for students who just missed public university cut-offs. Sunway, Taylor's, Monash KL, and HELP all run competitive scholarship programmes. Browse MyScholar for the full list.",
    intro_bm:"Universiti swasta di Malaysia menawarkan beberapa biasiswa merit yang paling mudah diakses — terutamanya untuk pelajar yang hampir terlepas potongan universiti awam. Sunway, Taylor's, Monash KL, dan HELP semua menjalankan program biasiswa yang kompetitif. Semak MyScholar untuk senarai penuh.",
    cta_en:"Browse Private University Scholarships",cta_bm:"Semak Biasiswa Universiti Swasta"}
},

// ============================================================
// === INTERNSHIP GAPS — GOVERNMENT, MEDIA, PHARMA, REMOTE ===
// ============================================================

{
  slug:"bank-negara-malaysia-internship-2026",type:"internship",
  keywords:{primary:"Bank Negara Malaysia internship 2026",primary_bm:"latihan industri Bank Negara Malaysia 2026",
    longtail_en:["BNM internship 2026","Bank Negara internship application Malaysia","Bank Negara graduate programme 2026","central bank internship Malaysia","BNM economics internship"],
    longtail_bm:["latihan industri BNM 2026","permohonan latihan industri Bank Negara Malaysia","program graduan Bank Negara 2026","latihan industri bank pusat Malaysia","latihan industri ekonomi BNM"]},
  meta:{title:"Bank Negara Malaysia Internship 2026 | MyScholar",title_bm:"Latihan Industri Bank Negara Malaysia 2026 | MyScholar",
    description:"Bank Negara Malaysia (BNM) internship 2026. Economics, finance, regulatory, and IT roles at Malaysia's central bank.",
    description_bm:"Latihan industri Bank Negara Malaysia (BNM) 2026. Peranan ekonomi, kewangan, kawal selia, dan IT di bank pusat Malaysia."},
  landing:{h1_en:"Bank Negara Malaysia Internship 2026",h1_bm:"Latihan Industri Bank Negara Malaysia 2026",
    intro_en:"BNM is Malaysia's central bank — and one of the most prestigious internship placements in the country. Economics, finance, monetary policy, and regulatory roles. Highly competitive but transformative for students interested in policy and macro-finance.",
    intro_bm:"BNM adalah bank pusat Malaysia — dan salah satu penempatan latihan industri paling berprestij di negara ini. Peranan ekonomi, kewangan, dasar monetari, dan kawal selia. Sangat kompetitif tetapi transformatif untuk pelajar yang berminat dalam dasar dan kewangan makro.",
    cta_en:"Find BNM Internship",cta_bm:"Cari Latihan Industri BNM"}
},
{
  slug:"securities-commission-internship-malaysia-2026",type:"internship",
  keywords:{primary:"Securities Commission Malaysia internship 2026",primary_bm:"latihan industri Suruhanjaya Sekuriti Malaysia 2026",
    longtail_en:["SC Malaysia internship 2026","securities regulator internship Malaysia","capital market internship Malaysia","SC Malaysia graduate programme","investment regulation internship KL"],
    longtail_bm:["latihan industri SC Malaysia 2026","latihan industri pengawal selia sekuriti Malaysia","latihan industri pasaran modal Malaysia","program graduan SC Malaysia","latihan industri regulasi pelaburan KL"]},
  meta:{title:"Securities Commission Malaysia Internship 2026 | MyScholar",title_bm:"Latihan Industri Suruhanjaya Sekuriti 2026 | MyScholar",
    description:"Securities Commission (SC) Malaysia internship 2026. Capital markets, regulation, fintech, and investment roles at Malaysia's market regulator.",
    description_bm:"Latihan industri Suruhanjaya Sekuriti (SC) Malaysia 2026. Peranan pasaran modal, kawal selia, fintech, dan pelaburan di pengawal selia pasaran Malaysia."},
  landing:{h1_en:"Securities Commission Malaysia Internship 2026",h1_bm:"Latihan Industri Suruhanjaya Sekuriti 2026",
    intro_en:"The Securities Commission regulates Malaysia's capital markets. Internship roles cover market surveillance, corporate finance, fintech regulation, and investor protection. An exceptional placement for finance, law, and economics students.",
    intro_bm:"Suruhanjaya Sekuriti mengawal selia pasaran modal Malaysia. Peranan latihan industri merangkumi pengawasan pasaran, kewangan korporat, regulasi fintech, dan perlindungan pelabur. Penempatan yang luar biasa untuk pelajar kewangan, undang-undang, dan ekonomi.",
    cta_en:"Find SC Internship",cta_bm:"Cari Latihan Industri SC"}
},
{
  slug:"bursa-malaysia-internship-2026",type:"internship",
  keywords:{primary:"Bursa Malaysia internship 2026",primary_bm:"latihan industri Bursa Malaysia 2026",
    longtail_en:["Bursa Malaysia internship application 2026","stock exchange internship Malaysia","Bursa Malaysia graduate programme","capital market internship Bursa","Bursa Malaysia IT internship 2026"],
    longtail_bm:["permohonan latihan industri Bursa Malaysia 2026","latihan industri bursa saham Malaysia","program graduan Bursa Malaysia","latihan industri pasaran modal Bursa","latihan industri IT Bursa Malaysia 2026"]},
  meta:{title:"Bursa Malaysia Internship 2026 | MyScholar",title_bm:"Latihan Industri Bursa Malaysia 2026 | MyScholar",
    description:"Bursa Malaysia internship 2026. Stock exchange, capital markets, IT, and operations roles at Malaysia's national stock exchange.",
    description_bm:"Latihan industri Bursa Malaysia 2026. Peranan bursa saham, pasaran modal, IT, dan operasi di bursa saham nasional Malaysia."},
  landing:{h1_en:"Bursa Malaysia Internship 2026",h1_bm:"Latihan Industri Bursa Malaysia 2026",
    intro_en:"Bursa Malaysia operates the country's stock exchange. Internship roles span market operations, IT systems, corporate listings support, and investor relations. Strong brand and unique exposure to how capital markets actually work.",
    intro_bm:"Bursa Malaysia mengendalikan bursa saham negara. Peranan latihan industri merangkumi operasi pasaran, sistem IT, sokongan penyenaraian korporat, dan hubungan pelabur. Jenama yang kukuh dan pendedahan unik kepada cara pasaran modal sebenarnya berfungsi.",
    cta_en:"Find Bursa Malaysia Internship",cta_bm:"Cari Latihan Industri Bursa Malaysia"}
},
{
  slug:"pharmaceutical-internship-malaysia-2026",type:"internship",
  keywords:{primary:"pharmaceutical internship Malaysia 2026",primary_bm:"latihan industri farmaseutikal Malaysia 2026",
    longtail_en:["pharma internship Malaysia 2026","AstraZeneca internship Malaysia","Pfizer internship Malaysia","pharmacy student internship Malaysia","clinical research internship Malaysia"],
    longtail_bm:["latihan industri farma Malaysia 2026","latihan industri AstraZeneca Malaysia","latihan industri Pfizer Malaysia","latihan industri pelajar farmasi Malaysia","latihan industri penyelidikan klinikal Malaysia"]},
  meta:{title:"Pharmaceutical Internship Malaysia 2026 | MyScholar",title_bm:"Latihan Industri Farmaseutikal Malaysia 2026 | MyScholar",
    description:"Pharmaceutical and pharma internships in Malaysia 2026. AstraZeneca, Pfizer, and local pharma company roles for pharmacy and life science students.",
    description_bm:"Latihan industri farmaseutikal dan farma di Malaysia 2026. Peranan AstraZeneca, Pfizer, dan syarikat farma tempatan untuk pelajar farmasi dan sains hayat."},
  landing:{h1_en:"Pharmaceutical Internship Malaysia 2026",h1_bm:"Latihan Industri Farmaseutikal Malaysia 2026",
    intro_en:"Malaysia is an active pharmaceutical manufacturing hub with global companies like AstraZeneca, Pfizer, and Hovid operating locally. Internship roles include regulatory affairs, clinical research, QA/QC, and sales. Essential for pharmacy and biomedical science students.",
    intro_bm:"Malaysia adalah hab pembuatan farmaseutikal aktif dengan syarikat global seperti AstraZeneca, Pfizer, dan Hovid beroperasi secara tempatan. Peranan latihan industri termasuk hal ehwal kawal selia, penyelidikan klinikal, QA/QC, dan jualan. Penting untuk pelajar farmasi dan sains bioperubatan.",
    cta_en:"Find Pharma Internships",cta_bm:"Cari Latihan Industri Farma"}
},
{
  slug:"media-journalism-internship-malaysia-2026",type:"internship",
  keywords:{primary:"media journalism internship Malaysia 2026",primary_bm:"latihan industri media kewartawanan Malaysia 2026",
    longtail_en:["journalism internship Malaysia 2026","media internship KL Malaysia","Astro internship Malaysia","Bernama internship 2026","New Straits Times internship Malaysia"],
    longtail_bm:["latihan industri kewartawanan Malaysia 2026","latihan industri media KL Malaysia","latihan industri Astro Malaysia","latihan industri Bernama 2026","latihan industri New Straits Times Malaysia"]},
  meta:{title:"Media & Journalism Internship Malaysia 2026 | MyScholar",title_bm:"Latihan Industri Media & Kewartawanan Malaysia 2026 | MyScholar",
    description:"Media and journalism internships in Malaysia 2026. Astro, Bernama, The Star, NST, and digital media company roles for mass comm students.",
    description_bm:"Latihan industri media dan kewartawanan di Malaysia 2026. Peranan Astro, Bernama, The Star, NST, dan syarikat media digital untuk pelajar komunikasi massa."},
  landing:{h1_en:"Media & Journalism Internship Malaysia 2026",h1_bm:"Latihan Industri Media & Kewartawanan Malaysia 2026",
    intro_en:"Malaysia's media landscape spans broadcast (Astro, RTM), national news (Bernama), and growing digital outlets. Internship roles in journalism, production, digital content, and communications are available across KL for mass comm and creative students.",
    intro_bm:"Landskap media Malaysia merangkumi penyiaran (Astro, RTM), berita nasional (Bernama), dan media digital yang berkembang. Peranan latihan industri dalam kewartawanan, pengeluaran, kandungan digital, dan komunikasi tersedia merentasi KL untuk pelajar komunikasi massa dan kreatif.",
    cta_en:"Find Media Internships",cta_bm:"Cari Latihan Industri Media"}
},
{
  slug:"paid-internship-malaysia-2026",type:"internship",
  keywords:{primary:"paid internship Malaysia 2026",primary_bm:"latihan industri berbayar Malaysia 2026",
    longtail_en:["high paying internship Malaysia 2026","internship with allowance Malaysia","internship stipend Malaysia 2026","best paid internships Malaysia","internship RM1000 allowance Malaysia"],
    longtail_bm:["latihan industri gaji tinggi Malaysia 2026","latihan industri dengan elaun Malaysia","elaun latihan industri Malaysia 2026","latihan industri terbaik berbayar Malaysia","latihan industri elaun RM1000 Malaysia"]},
  meta:{title:"Paid Internships Malaysia 2026 | MyScholar",title_bm:"Latihan Industri Berbayar Malaysia 2026 | MyScholar",
    description:"Paid internships in Malaysia 2026. Find internships with competitive allowances across banking, tech, oil & gas, and MNC companies.",
    description_bm:"Latihan industri berbayar di Malaysia 2026. Cari latihan industri dengan elaun kompetitif merentasi perbankan, teknologi, minyak & gas, dan syarikat MNC."},
  landing:{h1_en:"Paid Internships in Malaysia 2026",h1_bm:"Latihan Industri Berbayar Malaysia 2026",
    intro_en:"Not all internships pay the same. In Malaysia, oil & gas (Petronas, Shell), Big 4 accounting, and MNC tech firms (Intel, Bosch) pay the highest allowances. MyScholar's internship directory includes allowance information where available — so you can filter by what you need.",
    intro_bm:"Tidak semua latihan industri membayar sama. Di Malaysia, minyak & gas (Petronas, Shell), perakaunan Big 4, dan firma teknologi MNC (Intel, Bosch) membayar elaun tertinggi. Direktori latihan industri MyScholar termasuk maklumat elaun di mana tersedia — supaya anda boleh menapis mengikut keperluan anda.",
    cta_en:"Find Paid Internships",cta_bm:"Cari Latihan Industri Berbayar"}
},
{
  slug:"remote-internship-malaysia-2026",type:"internship",
  keywords:{primary:"remote internship Malaysia 2026",primary_bm:"latihan industri kerja dari rumah Malaysia 2026",
    longtail_en:["work from home internship Malaysia 2026","online internship Malaysia 2026","virtual internship Malaysia","remote internship KL Malaysia","digital internship Malaysia 2026"],
    longtail_bm:["latihan industri kerja dari rumah Malaysia 2026","latihan industri dalam talian Malaysia 2026","latihan industri maya Malaysia","latihan industri jauh KL Malaysia","latihan industri digital Malaysia 2026"]},
  meta:{title:"Remote Internships Malaysia 2026 | MyScholar",title_bm:"Latihan Industri Kerja Dari Rumah Malaysia 2026 | MyScholar",
    description:"Remote and work-from-home internships in Malaysia 2026. Digital, tech, marketing, and content creation roles you can do from anywhere.",
    description_bm:"Latihan industri kerja dari rumah di Malaysia 2026. Peranan digital, teknologi, pemasaran, dan penciptaan kandungan yang boleh anda lakukan dari mana sahaja."},
  landing:{h1_en:"Remote Internships in Malaysia 2026",h1_bm:"Latihan Industri Kerja Dari Rumah Malaysia 2026",
    intro_en:"Remote internships became normal after 2020 — and many Malaysian companies now offer full WFH placements. Digital marketing, content creation, software development, and data analysis roles are particularly suited to remote formats. Browse MyScholar's remote-tagged internships.",
    intro_bm:"Latihan industri jauh menjadi normal selepas 2020 — dan banyak syarikat Malaysia kini menawarkan penempatan sepenuhnya WFH. Pemasaran digital, penciptaan kandungan, pembangunan perisian, dan peranan analisis data sangat sesuai untuk format jauh. Semak latihan industri bertag jauh MyScholar.",
    cta_en:"Find Remote Internships",cta_bm:"Cari Latihan Industri Kerja Dari Rumah"}
},
{
  slug:"startup-internship-kl-2026",type:"internship",
  keywords:{primary:"startup internship KL Malaysia 2026",primary_bm:"latihan industri syarikat permulaan KL Malaysia 2026",
    longtail_en:["tech startup internship Kuala Lumpur 2026","fintech internship KL Malaysia","e-commerce startup internship Malaysia","startup internship MDEC Malaysia","Silicon Valley Malaysia internship"],
    longtail_bm:["latihan industri syarikat permulaan teknologi KL 2026","latihan industri fintech KL Malaysia","latihan industri permulaan e-dagang Malaysia","latihan industri permulaan MDEC Malaysia","latihan industri Silicon Valley Malaysia"]},
  meta:{title:"Startup Internship KL 2026 | MyScholar",title_bm:"Latihan Industri Syarikat Permulaan KL 2026 | MyScholar",
    description:"Startup internships in Kuala Lumpur 2026. Fintech, e-commerce, and tech startup roles across KL's growing startup ecosystem.",
    description_bm:"Latihan industri syarikat permulaan di Kuala Lumpur 2026. Peranan fintech, e-dagang, dan syarikat permulaan teknologi merentasi ekosistem permulaan KL yang berkembang."},
  landing:{h1_en:"Startup Internships in KL 2026",h1_bm:"Latihan Industri Syarikat Permulaan KL 2026",
    intro_en:"KL has a growing startup scene — Grab, Carsome, and StoreHub all started here. Startup internships are different from MNC ones: broader role, faster learning, less structure. Good for students who want to build product, growth, or engineering skills fast.",
    intro_bm:"KL mempunyai pemandangan permulaan yang berkembang — Grab, Carsome, dan StoreHub semua bermula di sini. Latihan industri permulaan berbeza daripada MNC: peranan lebih luas, pembelajaran lebih cepat, kurang struktur. Sesuai untuk pelajar yang ingin membina kemahiran produk, pertumbuhan, atau kejuruteraan dengan cepat.",
    cta_en:"Find Startup Internships KL",cta_bm:"Cari Latihan Industri Startup KL"}
},
{
  slug:"internship-kota-kinabalu-2026",type:"internship",
  keywords:{primary:"internship Kota Kinabalu Sabah 2026",primary_bm:"latihan industri Kota Kinabalu Sabah 2026",
    longtail_en:["internship KK Sabah 2026","Sabah internship opportunities 2026","government internship Kota Kinabalu","internship Sabah 2026 for students","oil gas internship Sabah Malaysia"],
    longtail_bm:["latihan industri KK Sabah 2026","peluang latihan industri Sabah 2026","latihan industri kerajaan Kota Kinabalu","latihan industri Sabah 2026 untuk pelajar","latihan industri minyak gas Sabah Malaysia"]},
  meta:{title:"Internship Kota Kinabalu Sabah 2026 | MyScholar",title_bm:"Latihan Industri Kota Kinabalu Sabah 2026 | MyScholar",
    description:"Internships in Kota Kinabalu (KK) and Sabah 2026. Oil & gas, government, tourism, and business internship opportunities in East Malaysia.",
    description_bm:"Latihan industri di Kota Kinabalu (KK) dan Sabah 2026. Peluang latihan industri minyak & gas, kerajaan, pelancongan, dan perniagaan di Malaysia Timur."},
  landing:{h1_en:"Internships in Kota Kinabalu & Sabah 2026",h1_bm:"Latihan Industri Kota Kinabalu & Sabah 2026",
    intro_en:"Sabah students shouldn't have to relocate to KL for a good internship. KK and the Sabah corridor have opportunities in oil & gas, government agencies, tourism, and agribusiness. MyScholar is building East Malaysia coverage — these listings are early but growing.",
    intro_bm:"Pelajar Sabah tidak perlu berpindah ke KL untuk latihan industri yang baik. KK dan koridor Sabah mempunyai peluang dalam minyak & gas, agensi kerajaan, pelancongan, dan agroperniagaan. MyScholar sedang membina liputan Malaysia Timur — senarai ini adalah awal tetapi berkembang.",
    cta_en:"Find KK & Sabah Internships",cta_bm:"Cari Latihan Industri KK & Sabah"}
},
{
  slug:"internship-kuching-sarawak-2026",type:"internship",
  keywords:{primary:"internship Kuching Sarawak 2026",primary_bm:"latihan industri Kuching Sarawak 2026",
    longtail_en:["Sarawak internship 2026","internship Kuching for students","oil gas internship Sarawak","government internship Sarawak","Shell Sarawak internship 2026"],
    longtail_bm:["latihan industri Sarawak 2026","latihan industri Kuching untuk pelajar","latihan industri minyak gas Sarawak","latihan industri kerajaan Sarawak","latihan industri Shell Sarawak 2026"]},
  meta:{title:"Internship Kuching Sarawak 2026 | MyScholar",title_bm:"Latihan Industri Kuching Sarawak 2026 | MyScholar",
    description:"Internships in Kuching and Sarawak 2026. Oil & gas, Shell, Petros, government, and business roles in East Malaysia's largest state.",
    description_bm:"Latihan industri di Kuching dan Sarawak 2026. Peranan minyak & gas, Shell, Petros, kerajaan, dan perniagaan di negeri terbesar Malaysia Timur."},
  landing:{h1_en:"Internships in Kuching & Sarawak 2026",h1_bm:"Latihan Industri Kuching & Sarawak 2026",
    intro_en:"Sarawak has significant oil & gas activity — Shell operates major facilities here, and Petros is the state's energy company. Beyond energy, Kuching has government agencies, a growing tech scene, and logistics opportunities. MyScholar is adding East Malaysia coverage progressively.",
    intro_bm:"Sarawak mempunyai aktiviti minyak & gas yang signifikan — Shell mengendalikan kemudahan utama di sini, dan Petros adalah syarikat tenaga negeri. Di luar tenaga, Kuching mempunyai agensi kerajaan, pemandangan teknologi yang berkembang, dan peluang logistik. MyScholar menambah liputan Malaysia Timur secara progresif.",
    cta_en:"Find Kuching & Sarawak Internships",cta_bm:"Cari Latihan Industri Kuching & Sarawak"}
},
{
  slug:"internship-shah-alam-2026",type:"internship",
  keywords:{primary:"internship Shah Alam 2026",primary_bm:"latihan industri Shah Alam 2026",
    longtail_en:["Shah Alam internship Selangor 2026","internship near UiTM Shah Alam","manufacturing internship Shah Alam","industrial internship Shah Alam","engineering internship Shah Alam 2026"],
    longtail_bm:["latihan industri Shah Alam Selangor 2026","latihan industri berdekatan UiTM Shah Alam","latihan industri pembuatan Shah Alam","latihan industri perindustrian Shah Alam","latihan industri kejuruteraan Shah Alam 2026"]},
  meta:{title:"Internship Shah Alam 2026 | MyScholar",title_bm:"Latihan Industri Shah Alam 2026 | MyScholar",
    description:"Internships in Shah Alam, Selangor 2026. Manufacturing, engineering, and business roles near UiTM, HICOM, and Shah Alam industrial areas.",
    description_bm:"Latihan industri di Shah Alam, Selangor 2026. Peranan pembuatan, kejuruteraan, dan perniagaan berdekatan UiTM, HICOM, dan kawasan perindustrian Shah Alam."},
  landing:{h1_en:"Internships in Shah Alam 2026",h1_bm:"Latihan Industri Shah Alam 2026",
    intro_en:"Shah Alam is Selangor's state capital and a major manufacturing hub — Honda, DRB-HICOM, Nestlé, and many industrial players are based here. Great for engineering, manufacturing, and operations interns. Strong fit for UiTM and UITM-adjacent students.",
    intro_bm:"Shah Alam adalah ibu negeri Selangor dan hab pembuatan utama — Honda, DRB-HICOM, Nestlé, dan ramai pemain perindustrian berpangkalan di sini. Sesuai untuk pelatih kejuruteraan, pembuatan, dan operasi. Sangat sesuai untuk pelajar UiTM dan berdekatan UiTM.",
    cta_en:"Find Shah Alam Internships",cta_bm:"Cari Latihan Industri Shah Alam"}
},
{
  slug:"healthcare-internship-malaysia-2026",type:"internship",
  keywords:{primary:"healthcare internship Malaysia 2026",primary_bm:"latihan industri penjagaan kesihatan Malaysia 2026",
    longtail_en:["hospital internship Malaysia 2026","medical internship Malaysia students","health sciences internship Malaysia","Pantai Hospital internship","KPJ internship Malaysia 2026"],
    longtail_bm:["latihan industri hospital Malaysia 2026","latihan industri perubatan pelajar Malaysia","latihan industri sains kesihatan Malaysia","latihan industri Hospital Pantai","latihan industri KPJ Malaysia 2026"]},
  meta:{title:"Healthcare Internship Malaysia 2026 | MyScholar",title_bm:"Latihan Industri Penjagaan Kesihatan Malaysia 2026 | MyScholar",
    description:"Healthcare and hospital internships in Malaysia 2026. Pantai, KPJ, Sunway Medical, and government hospital roles for health science students.",
    description_bm:"Latihan industri penjagaan kesihatan dan hospital di Malaysia 2026. Peranan Pantai, KPJ, Sunway Medical, dan hospital kerajaan untuk pelajar sains kesihatan."},
  landing:{h1_en:"Healthcare Internships in Malaysia 2026",h1_bm:"Latihan Industri Penjagaan Kesihatan Malaysia 2026",
    intro_en:"Malaysia's private hospital chains — Pantai, KPJ, and Sunway Medical — all run internship programmes for healthcare students. Roles span nursing, pharmacy, medical imaging, health management, and administrative functions. Essential for health sciences students.",
    intro_bm:"Rangkaian hospital swasta Malaysia — Pantai, KPJ, dan Sunway Medical — semua menjalankan program latihan industri untuk pelajar penjagaan kesihatan. Peranan merangkumi kejururawatan, farmasi, pengimejan perubatan, pengurusan kesihatan, dan fungsi pentadbiran. Penting untuk pelajar sains kesihatan.",
    cta_en:"Find Healthcare Internships",cta_bm:"Cari Latihan Industri Penjagaan Kesihatan"}
},

]; // end module.exports
